<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('courses') || ! Schema::hasTable('course_translations') || ! Schema::hasTable('program_courses')) {
            return;
        }

        foreach ($this->translations() as $code => $translations) {
            $courseId = DB::table('courses')->where('code', $code)->value('id');

            if (! $courseId || ! DB::table('program_courses')->where('course_id', $courseId)->exists()) {
                continue;
            }

            foreach ($translations as $locale => $name) {
                DB::table('course_translations')->updateOrInsert(
                    ['course_id' => $courseId, 'locale' => $locale],
                    [
                        'name' => $name,
                        'updated_at' => now(),
                        'created_at' => now(),
                    ],
                );
            }
        }
    }

    public function down(): void
    {
        // Course localization normalization is intentionally not destructive.
    }

    private function translations(): array
    {
        return [
            'ACAD-102' => ['en' => 'Academic Skills and Professional Competence', 'uz' => 'Akademik ko‘nikmalar va kasbiy kompetensiya', 'ru' => 'Академические навыки и профессиональная компетентность', 'ar' => 'المهارات الأكاديمية والكفاءة المهنية'],
            'ACCO-123' => ['en' => 'Accounting', 'uz' => 'Buxgalteriya hisobi', 'ru' => 'Бухгалтерский учет', 'ar' => 'المحاسبة'],
            'ALGO-122' => ['en' => 'Algorithmic Languages and Programming', 'uz' => 'Algoritmik tillar va dasturlash', 'ru' => 'Алгоритмические языки и программирование', 'ar' => 'اللغات الخوارزمية والبرمجة'],
            'ARCH-100' => ['en' => 'Architectural Composition and Basics of Design', 'uz' => 'Me’moriy kompozitsiya va loyihalash asoslari', 'ru' => 'Архитектурная композиция и основы проектирования', 'ar' => 'التكوين المعماري وأسس التصميم'],
            'ARCH-101' => ['en' => 'Architectural Drawing, Painting and Sculpture', 'uz' => 'Me’moriy chizma, rangtasvir va haykaltaroshlik', 'ru' => 'Архитектурный рисунок, живопись и скульптура', 'ar' => 'الرسم المعماري والتلوين والنحت'],
            'ARCH-102' => ['en' => 'Architectural Design', 'uz' => 'Me’moriy loyihalash', 'ru' => 'Архитектурное проектирование', 'ar' => 'التصميم المعماري'],
            'ARCH-110' => ['en' => 'Architecture of Industrial and Civil Buildings (Industrial Buildings)', 'uz' => 'Sanoat va fuqarolik binolari arxitekturasi', 'ru' => 'Архитектура промышленных и гражданских зданий', 'ar' => 'عمارة المباني الصناعية والسكنية'],
            'ARCH-114' => ['en' => 'Architectural Heritage of Uzbekistan', 'uz' => 'O‘zbekiston me’moriy merosi', 'ru' => 'Архитектурное наследие Узбекистана', 'ar' => 'التراث المعماري لأوزبكستان'],
            'ARTI-107' => ['en' => 'Artificial Intelligence Systems', 'uz' => 'Sun’iy intellekt tizimlari', 'ru' => 'Системы искусственного интеллекта', 'ar' => 'أنظمة الذكاء الاصطناعي'],
            'ARTI-151' => ['en' => 'Artificial Intelligence Fundamentals', 'uz' => 'Sun’iy intellekt asoslari', 'ru' => 'Основы искусственного интеллекта', 'ar' => 'أساسيات الذكاء الاصطناعي'],
            'AUTO-108' => ['en' => 'Automated Design of Information Systems', 'uz' => 'Axborot tizimlarini avtomatlashtirilgan loyihalash', 'ru' => 'Автоматизированное проектирование информационных систем', 'ar' => 'التصميم الآلي لأنظمة المعلومات'],
            'AUTO-110' => ['en' => 'Automated Systems of Electricity Accounting and Control', 'uz' => 'Elektr energiyasini hisobga olish va nazorat qilish avtomatlashtirilgan tizimlari', 'ru' => 'Автоматизированные системы учета и контроля электроэнергии', 'ar' => 'الأنظمة الآلية لحساب ومراقبة الكهرباء'],
            'BAKE-109' => ['en' => 'Bakery, pasta and confectionery equipment', 'uz' => 'Non, makaron va qandolat mahsulotlari jihozlari', 'ru' => 'Оборудование хлебопекарного, макаронного и кондитерского производства', 'ar' => 'معدات المخابز والمعكرونة والحلويات'],
            'BASI-112' => ['en' => 'Basics of Designing Energy-Saving and Energy-Efficient Buildings', 'uz' => 'Energiya tejamkor va energiya samarali binolarni loyihalash asoslari', 'ru' => 'Основы проектирования энергосберегающих и энергоэффективных зданий', 'ar' => 'أسس تصميم المباني الموفرة للطاقة وذات الكفاءة العالية'],
            'BIGD-130' => ['en' => 'Big Data Analysis', 'uz' => 'Katta ma’lumotlar tahlili', 'ru' => 'Анализ больших данных', 'ar' => 'تحليل البيانات الضخمة'],
            'BIGD-156' => ['en' => 'Big Data Management', 'uz' => 'Katta ma’lumotlarni boshqarish', 'ru' => 'Управление большими данными', 'ar' => 'إدارة البيانات الضخمة'],
            'BOIL-115' => ['en' => 'Boiler Facilities', 'uz' => 'Qozon qurilmalari', 'ru' => 'Котельные установки', 'ar' => 'منشآت الغلايات'],
            'BUSI-120' => ['en' => 'Business Strategy', 'uz' => 'Biznes strategiyasi', 'ru' => 'Бизнес-стратегия', 'ar' => 'استراتيجية الأعمال'],
            'BUSI-158' => ['en' => 'Business Process and IT Strategy', 'uz' => 'Biznes jarayonlari va IT strategiyasi', 'ru' => 'Бизнес-процессы и ИТ-стратегия', 'ar' => 'عمليات الأعمال واستراتيجية تقنية المعلومات'],
            'CHEM-105' => ['en' => 'Chemistry and Technology of Fuels and Oils', 'uz' => 'Yoqilg‘i va moylar kimyosi hamda texnologiyasi', 'ru' => 'Химия и технология топлив и масел', 'ar' => 'كيمياء وتكنولوجيا الوقود والزيوت'],
            'CLOU-138' => ['en' => 'Cloud Technology and Virtual Reality Systems', 'uz' => 'Bulut texnologiyalari va virtual reallik tizimlari', 'ru' => 'Облачные технологии и системы виртуальной реальности', 'ar' => 'تقنيات السحابة وأنظمة الواقع الافتراضي'],
            'CLOU-154' => ['en' => 'Cloud Technologies', 'uz' => 'Bulut texnologiyalari', 'ru' => 'Облачные технологии', 'ar' => 'تقنيات الحوسبة السحابية'],
            'COMP-101' => ['en' => 'Composition and properties of plant raw materials', 'uz' => 'O‘simlik xomashyosi tarkibi va xossalari', 'ru' => 'Состав и свойства растительного сырья', 'ar' => 'تركيب وخصائص المواد الخام النباتية'],
            'COMP-115' => ['en' => 'Computer Networks and Telecommunications', 'uz' => 'Kompyuter tarmoqlari va telekommunikatsiyalar', 'ru' => 'Компьютерные сети и телекоммуникации', 'ar' => 'شبكات الحاسوب والاتصالات'],
            'COMP-121' => ['en' => 'Computer Graphics, Infographics and Design', 'uz' => 'Kompyuter grafikasi, infografika va dizayn', 'ru' => 'Компьютерная графика, инфографика и дизайн', 'ar' => 'رسوم الحاسوب والإنفوغرافيك والتصميم'],
            'COMP-125' => ['en' => 'Computer Systems and Networks', 'uz' => 'Kompyuter tizimlari va tarmoqlari', 'ru' => 'Компьютерные системы и сети', 'ar' => 'أنظمة وشبكات الحاسوب'],
            'COMP-149' => ['en' => 'Computer Networks', 'uz' => 'Kompyuter tarmoqlari', 'ru' => 'Компьютерные сети', 'ar' => 'شبكات الحاسوب'],
            'CONS-102' => ['en' => 'Construction Organization and Planning', 'uz' => 'Qurilishni tashkil etish va rejalashtirish', 'ru' => 'Организация и планирование строительства', 'ar' => 'تنظيم وتخطيط أعمال البناء'],
            'CONS-111' => ['en' => 'Construction Processes Technology', 'uz' => 'Qurilish jarayonlari texnologiyasi', 'ru' => 'Технология строительных процессов', 'ar' => 'تكنولوجيا عمليات البناء والتشييد'],
            'CONS-118' => ['en' => 'Construction Machinery', 'uz' => 'Qurilish mashinalari', 'ru' => 'Строительные машины', 'ar' => 'آلات ومعدات البناء'],
            'CONS-138' => ['en' => 'Consumer Behavior', 'uz' => 'Iste’molchi xulq-atvori', 'ru' => 'Поведение потребителей', 'ar' => 'سلوك المستهلك'],
            'CONT-109' => ['en' => 'Control and Programming of Industrial Robots', 'uz' => 'Sanoat robotlarini boshqarish va dasturlash', 'ru' => 'Управление и программирование промышленных роботов', 'ar' => 'التحكم في الروبوتات الصناعية وبرمجتها'],
            'CONT-132' => ['en' => 'Control Theory', 'uz' => 'Boshqaruv nazariyasi', 'ru' => 'Теория управления', 'ar' => 'نظرية التحكم'],
            'CYBE-140' => ['en' => 'Cybersecurity Fundamentals', 'uz' => 'Kiberxavfsizlik asoslari', 'ru' => 'Основы кибербезопасности', 'ar' => 'أساسيات الأمن السيبراني'],
            'DATA-123' => ['en' => 'Database Management and Programming Technologies', 'uz' => 'Ma’lumotlar bazasini boshqarish va dasturlash texnologiyalari', 'ru' => 'Управление базами данных и технологии программирования', 'ar' => 'إدارة قواعد البيانات وتقنيات البرمجة'],
            'DATA-145' => ['en' => 'Data Structures and Algorithms', 'uz' => 'Ma’lumotlar tuzilmalari va algoritmlar', 'ru' => 'Структуры данных и алгоритмы', 'ar' => 'هياكل البيانات والخوارزميات'],
            'DATA-146' => ['en' => 'Databases', 'uz' => 'Ma’lumotlar bazalari', 'ru' => 'Базы данных', 'ar' => 'قواعد البيانات'],
            'DATA-162' => ['en' => 'Database Management Systems', 'uz' => 'Ma’lumotlar bazasini boshqarish tizimlari', 'ru' => 'Системы управления базами данных', 'ar' => 'أنظمة إدارة قواعد البيانات'],
            'DESI-103' => ['en' => 'Design of oil and gas processing enterprises', 'uz' => 'Neft va gazni qayta ishlash korxonalarini loyihalash', 'ru' => 'Проектирование предприятий переработки нефти и газа', 'ar' => 'تصميم منشآت معالجة النفط والغاز'],
            'DESI-110' => ['en' => 'Design Software for Industry Objects', 'uz' => 'Sanoat obyektlari uchun loyihalash dasturlari', 'ru' => 'Программное обеспечение проектирования промышленных объектов', 'ar' => 'برمجيات تصميم المنشآت الصناعية'],
            'DESI-134' => ['en' => 'Designing Information Systems', 'uz' => 'Axborot tizimlarini loyihalash', 'ru' => 'Проектирование информационных систем', 'ar' => 'تصميم أنظمة المعلومات'],
            'DIFF-150' => ['en' => 'Differential Equations', 'uz' => 'Differensial tenglamalar', 'ru' => 'Дифференциальные уравнения', 'ar' => 'المعادلات التفاضلية'],
            'DIGI-109' => ['en' => 'Digital Design (AutoCAD, SketchUp, Revit)', 'uz' => 'Raqamli loyihalash (AutoCAD, SketchUp, Revit)', 'ru' => 'Цифровое проектирование (AutoCAD, SketchUp, Revit)', 'ar' => 'التصميم الرقمي (AutoCAD، SketchUp، Revit)'],
            'DIGI-124' => ['en' => 'Digital Circuit Engineering', 'uz' => 'Raqamli sxemotexnika', 'ru' => 'Цифровая схемотехника', 'ar' => 'هندسة الدوائر الرقمية'],
            'DIGI-125' => ['en' => 'Digital Economy', 'uz' => 'Raqamli iqtisodiyot', 'ru' => 'Цифровая экономика', 'ar' => 'الاقتصاد الرقمي'],
            'DISC-106' => ['en' => 'Discrete, Digital Control Design Software and Systems', 'uz' => 'Diskret va raqamli boshqaruvni loyihalash dasturlari va tizimlari', 'ru' => 'Программы и системы проектирования дискретного и цифрового управления', 'ar' => 'برمجيات وأنظمة تصميم التحكم الرقمي والمنفصل'],
            'DISC-120' => ['en' => 'Discrete Mathematics and Mathematical Logic', 'uz' => 'Diskret matematika va matematik mantiq', 'ru' => 'Дискретная математика и математическая логика', 'ar' => 'الرياضيات المتقطعة والمنطق الرياضي'],
            'DISC-148' => ['en' => 'Discrete Structures', 'uz' => 'Diskret tuzilmalar', 'ru' => 'Дискретные структуры', 'ar' => 'البنى المتقطعة'],
            'DISC-165' => ['en' => 'Discrete and Digital Control Systems', 'uz' => 'Diskret va raqamli boshqaruv tizimlari', 'ru' => 'Дискретные и цифровые системы управления', 'ar' => 'أنظمة التحكم المنفصلة والرقمية'],
            'DISP-106' => ['en' => 'Disposal of oil and gas processing waste', 'uz' => 'Neft va gazni qayta ishlash chiqindilarini utilizatsiya qilish', 'ru' => 'Утилизация отходов переработки нефти и газа', 'ar' => 'التخلص من مخلفات معالجة النفط والغاز'],
            'DIST-113' => ['en' => 'District Planning and Design', 'uz' => 'Hududiy rejalashtirish va loyihalash', 'ru' => 'Районная планировка и проектирование', 'ar' => 'تخطيط وتصميم المناطق والمحافظات'],
            'ECON-100' => ['en' => 'Economic Theory', 'uz' => 'Iqtisodiy nazariya', 'ru' => 'Экономическая теория', 'ar' => 'النظرية الاقتصادية'],
            'ECON-103' => ['en' => 'Economic Analysis', 'uz' => 'Iqtisodiy tahlil', 'ru' => 'Экономический анализ', 'ar' => 'التحليل الاقتصادي'],
            'ECON-106' => ['en' => 'Econometrics', 'uz' => 'Ekonometrika', 'ru' => 'Эконометрика', 'ar' => 'الاقتصاد القياسي'],
            'ECON-116' => ['en' => 'Economic Security', 'uz' => 'Iqtisodiy xavfsizlik', 'ru' => 'Экономическая безопасность', 'ar' => 'الأمن الاقتصادي'],
            'ECON-122' => ['en' => 'Economic Geography and Ecology', 'uz' => 'Iqtisodiy geografiya va ekologiya', 'ru' => 'Экономическая география и экология', 'ar' => 'الجغرافيا الاقتصادية والبيئة'],
            'ELEC-102' => ['en' => 'Electrical Technological Devices', 'uz' => 'Elektrotexnologik qurilmalar', 'ru' => 'Электротехнологические установки', 'ar' => 'الأجهزة التقنية الكهربائية'],
            'ELEC-103' => ['en' => 'Electrical Machines / Electrical Devices', 'uz' => 'Elektr mashinalari / elektr qurilmalari', 'ru' => 'Электрические машины / Электрические приборы', 'ar' => 'الآلات الكهربائية / الأجهزة الكهربائية'],
            'ELEC-104' => ['en' => 'Electrical Lighting', 'uz' => 'Elektr yoritish', 'ru' => 'Электрическое освещение', 'ar' => 'الإضاءة الكهربائية'],
            'ELEC-105' => ['en' => 'Electricity Measuring and Control Instruments', 'uz' => 'Elektr energiyasini o‘lchash va nazorat qilish asboblari', 'ru' => 'Приборы измерения и контроля электроэнергии', 'ar' => 'أجهزة قياس ومراقبة الكهرباء'],
            'ELEC-106' => ['en' => 'Electrical Networks and Systems', 'uz' => 'Elektr tarmoqlari va tizimlari', 'ru' => 'Электрические сети и системы', 'ar' => 'الشبكات والأنظمة الكهربائية'],
            'ELEC-112' => ['en' => 'Electrical Engineering and Electronics', 'uz' => 'Elektrotexnika va elektronika', 'ru' => 'Электротехника и электроника', 'ar' => 'الهندسة الكهربائية والإلكترونيات'],
            'ELEC-113' => ['en' => 'Electronics and Circuit Engineering', 'uz' => 'Elektronika va sxemotexnika', 'ru' => 'Электроника и схемотехника', 'ar' => 'الإلكترونيات وهندسة الدوائر'],
            'ELEC-147' => ['en' => 'Electronics and Circuits', 'uz' => 'Elektronika va sxemalar', 'ru' => 'Электроника и цепи', 'ar' => 'الإلكترونيات والدوائر'],
            'ENER-101' => ['en' => 'Energy Management', 'uz' => 'Energiya menejmenti', 'ru' => 'Энергоменеджмент', 'ar' => 'إدارة الطاقة'],
            'ENER-111' => ['en' => 'Energy Saving Technologies in Oil and Gas Refining', 'uz' => 'Neft va gazni qayta ishlashda energiya tejovchi texnologiyalar', 'ru' => 'Энергосберегающие технологии в переработке нефти и газа', 'ar' => 'تقنيات توفير الطاقة في تكرير النفط والغاز'],
            'ENER-117' => ['en' => 'Energy Production Technologies and Centers', 'uz' => 'Energiya ishlab chiqarish texnologiyalari va markazlari', 'ru' => 'Технологии и центры производства энергии', 'ar' => 'تكنولوجيات ومراكز إنتاج الطاقة'],
            'ENGI-109' => ['en' => 'Engineering Geodesy', 'uz' => 'Muhandislik geodeziyasi', 'ru' => 'Инженерная геодезия', 'ar' => 'الجيوديسيا الهندسية وأعمال المساحة'],
            'ENGI-110' => ['en' => 'Engineering Equipment of Buildings', 'uz' => 'Binolarning muhandislik jihozlari', 'ru' => 'Инженерное оборудование зданий', 'ar' => 'المعدات الهندسية للمباني'],
            'ENGI-117' => ['en' => 'Engineering Geology and Hydrogeology', 'uz' => 'Muhandislik geologiyasi va gidrogeologiya', 'ru' => 'Инженерная геология и гидрогеология', 'ar' => 'الجيولوجيا الهندسية والهيدرولوجيا'],
            'ENGI-135' => ['en' => 'Engineering Software', 'uz' => 'Muhandislik dasturiy ta’minoti', 'ru' => 'Инженерное программное обеспечение', 'ar' => 'البرمجيات الهندسية'],
            'ENTE-119' => ['en' => 'Enterprise Economics', 'uz' => 'Korxona iqtisodiyoti', 'ru' => 'Экономика предприятия', 'ar' => 'اقتصاد المؤسسة'],
            'ENTR-130' => ['en' => 'Entrepreneurship Management', 'uz' => 'Tadbirkorlikni boshqarish', 'ru' => 'Управление предпринимательством', 'ar' => 'إدارة ريادة الأعمال'],
            'ENVI-129' => ['en' => 'Environmental Management', 'uz' => 'Ekologik menejment', 'ru' => 'Экологический менеджмент', 'ar' => 'الإدارة البيئية'],
            'EQUI-102' => ['en' => 'Equipment for oil and gas processing', 'uz' => 'Neft va gazni qayta ishlash uskunalari', 'ru' => 'Оборудование для переработки нефти и газа', 'ar' => 'معدات معالجة النفط والغاز'],
            'ESTI-116' => ['en' => 'Estimation and Smeta in Construction', 'uz' => 'Qurilishda smeta va xarajatlarni baholash', 'ru' => 'Сметное дело в строительстве', 'ar' => 'حساب الكميات والتقدير المالي في البناء'],
            'FINA-114' => ['en' => 'Finance', 'uz' => 'Moliya', 'ru' => 'Финансы', 'ar' => 'التمويل'],
            'FINI-106' => ['en' => 'Finishing Building Materials Technology', 'uz' => 'Pardozlash qurilish materiallari texnologiyasi', 'ru' => 'Технология отделочных строительных материалов', 'ar' => 'تكنولوجيا مواد التشطيب والطلاء'],
            'FOOD-102' => ['en' => 'Food biochemistry', 'uz' => 'Oziq-ovqat biokimyosi', 'ru' => 'Биохимия пищевых продуктов', 'ar' => 'الكيمياء الحيوية للأغذية'],
            'FOOD-103' => ['en' => 'Food commodity science', 'uz' => 'Oziq-ovqat tovarshunosligi', 'ru' => 'Товароведение пищевых продуктов', 'ar' => 'علم السلع الغذائية'],
            'FOOD-104' => ['en' => 'Food examination', 'uz' => 'Oziq-ovqat ekspertizasi', 'ru' => 'Экспертиза пищевых продуктов', 'ar' => 'فحص الأغذية'],
            'FOOD-105' => ['en' => 'Food raw materials and materials commodity science', 'uz' => 'Oziq-ovqat xomashyosi va materiallari tovarshunosligi', 'ru' => 'Товароведение пищевого сырья и материалов', 'ar' => 'علم سلع المواد الخام والمواد الغذائية'],
            'FOOD-106' => ['en' => 'Food microbiology', 'uz' => 'Oziq-ovqat mikrobiologiyasi', 'ru' => 'Пищевая микробиология', 'ar' => 'ميكروبيولوجيا الأغذية'],
            'FOOD-108' => ['en' => 'Food research methods', 'uz' => 'Oziq-ovqat tadqiqot usullari', 'ru' => 'Методы исследования пищевых продуктов', 'ar' => 'طرق البحث في الأغذية'],
            'FUEL-113' => ['en' => 'Fuel Combustion and Water Treatment Technology in TPP', 'uz' => 'IESda yoqilg‘i yonishi va suv tayyorlash texnologiyasi', 'ru' => 'Технология сжигания топлива и водоподготовки на ТЭС', 'ar' => 'تكنولوجيا احتراق الوقود ومعالجة المياه في محطات الطاقة الحرارية'],
            'FUEL-119' => ['en' => 'Fuel and Combustion', 'uz' => 'Yoqilg‘i va yonish', 'ru' => 'Топливо и горение', 'ar' => 'الوقود والاحتراق'],
            'FUND-100' => ['en' => 'Fundamentals of modern professional technology', 'uz' => 'Zamonaviy kasbiy texnologiya asoslari', 'ru' => 'Основы современных профессиональных технологий', 'ar' => 'أساسيات التكنولوجيا المهنية الحديثة'],
            'FUND-104' => ['en' => 'Fundamentals of Design Activity', 'uz' => 'Loyihalash faoliyati asoslari', 'ru' => 'Основы проектной деятельности', 'ar' => 'أساسيات نشاط التصميم'],
            'FUND-143' => ['en' => 'Fundamentals of Systems Analysis', 'uz' => 'Tizimli tahlil asoslari', 'ru' => 'Основы системного анализа', 'ar' => 'أساسيات تحليل النظم'],
            'GENE-104' => ['en' => 'General Chemical Technology', 'uz' => 'Umumiy kimyoviy texnologiya', 'ru' => 'Общая химическая технология', 'ar' => 'التكنولوجيا الكيميائية العامة'],
            'GREE-121' => ['en' => 'Green Economy', 'uz' => 'Yashil iqtisodiyot', 'ru' => 'Зеленая экономика', 'ar' => 'الاقتصاد الأخضر'],
            'HEAT-111' => ['en' => 'Heat Engineering', 'uz' => 'Issiqlik texnikasi', 'ru' => 'Теплотехника', 'ar' => 'الهندسة الحرارية'],
            'HEAT-114' => ['en' => 'Heat Engineering Measuring and Control Instruments', 'uz' => 'Issiqlik texnikasida o‘lchash va nazorat asboblari', 'ru' => 'Приборы измерения и контроля теплотехники', 'ar' => 'أجهزة قياس ومراقبة الهندسة الحرارية'],
            'HIGH-116' => ['en' => 'High-Temperature Processes and Devices', 'uz' => 'Yuqori haroratli jarayonlar va qurilmalar', 'ru' => 'Высокотемпературные процессы и установки', 'ar' => 'العمليات والأجهزة ذات الحرارة العالية'],
            'HUMA-124' => ['en' => 'Human Resource Management', 'uz' => 'Inson resurslarini boshqarish', 'ru' => 'Управление человеческими ресурсами', 'ar' => 'إدارة الموارد البشرية'],
            'HYDR-109' => ['en' => 'Hydrocarbon Gas Processing Technology', 'uz' => 'Uglevodorod gazlarini qayta ishlash texnologiyasi', 'ru' => 'Технология переработки углеводородных газов', 'ar' => 'تكنولوجيا معالجة الغازات الهيدروكربونية'],
            'IDEN-117' => ['en' => 'Identification, Modeling, and Optimization', 'uz' => 'Identifikatsiya, modellashtirish va optimallashtirish', 'ru' => 'Идентификация, моделирование и оптимизация', 'ar' => 'التعريف والنمذجة والتحسين'],
            'INDI-157' => ['en' => 'Individual Project', 'uz' => 'Individual loyiha', 'ru' => 'Индивидуальный проект', 'ar' => 'مشروع فردي'],
            'INFO-105' => ['en' => 'Information Systems in Enterprise', 'uz' => 'Korxonadagi axborot tizimlari', 'ru' => 'Информационные системы на предприятии', 'ar' => 'أنظمة المعلومات في المؤسسة'],
            'INFO-119' => ['en' => 'Information Communication Systems and Technologies', 'uz' => 'Axborot-kommunikatsiya tizimlari va texnologiyalari', 'ru' => 'Информационно-коммуникационные системы и технологии', 'ar' => 'أنظمة وتقنيات المعلومات والاتصالات'],
            'INFO-153' => ['en' => 'Information System Development Methodologies', 'uz' => 'Axborot tizimlarini ishlab chiqish metodologiyalari', 'ru' => 'Методологии разработки информационных систем', 'ar' => 'منهجيات تطوير أنظمة المعلومات'],
            'INFO-159' => ['en' => 'Information Systems Data Visualization', 'uz' => 'Axborot tizimlarida ma’lumotlarni vizualizatsiya qilish', 'ru' => 'Визуализация данных информационных систем', 'ar' => 'تصوير بيانات أنظمة المعلومات'],
            'INNO-104' => ['en' => 'Innovative Technologies in Construction Industry', 'uz' => 'Qurilish sanoatida innovatsion texnologiyalar', 'ru' => 'Инновационные технологии в строительной индустрии', 'ar' => 'التقنيات المبتكرة في صناعة البناء والتشييد'],
            'INNO-117' => ['en' => 'Innovation Management', 'uz' => 'Innovatsion menejment', 'ru' => 'Инновационный менеджмент', 'ar' => 'إدارة الابتكار'],
            'INST-107' => ['en' => 'Installation and Operation of Power Supply System', 'uz' => 'Elektr ta’minoti tizimini montaj qilish va ekspluatatsiya qilish', 'ru' => 'Монтаж и эксплуатация систем электроснабжения', 'ar' => 'تركيب وتشغيل أنظمة إمداد الطاقة'],
            'INST-118' => ['en' => 'Instrumental Tools of Information Management Systems', 'uz' => 'Axborot boshqaruv tizimlarining instrumental vositalari', 'ru' => 'Инструментальные средства информационных управляющих систем', 'ar' => 'الأدوات التطبيقية لأنظمة إدارة المعلومات'],
            'INTE-107' => ['en' => 'Interior and Equipment', 'uz' => 'Interyer va jihozlar', 'ru' => 'Интерьер и оборудование', 'ar' => 'التصميم الداخلي والمعدات'],
            'INTE-133' => ['en' => 'Intelligent Information Systems', 'uz' => 'Intellektual axborot tizimlari', 'ru' => 'Интеллектуальные информационные системы', 'ar' => 'أنظمة المعلومات الذكية'],
            'INTE-134' => ['en' => 'International Management', 'uz' => 'Xalqaro menejment', 'ru' => 'Международный менеджмент', 'ar' => 'الإدارة الدولية'],
            'INTE-166' => ['en' => 'Intelligent Control Theory', 'uz' => 'Intellektual boshqaruv nazariyasi', 'ru' => 'Теория интеллектуального управления', 'ar' => 'نظرية التحكم الذكي'],
            'INTR-100' => ['en' => 'Introduction to specialization', 'uz' => 'Mutaxassislikka kirish', 'ru' => 'Введение в специальность', 'ar' => 'مدخل إلى التخصص'],
            'INTR-101' => ['en' => 'Introduction to Business', 'uz' => 'Biznesga kirish', 'ru' => 'Введение в бизнес', 'ar' => 'مدخل إلى الأعمال'],
            'INTR-107' => ['en' => 'Introduction to Management', 'uz' => 'Menejmentga kirish', 'ru' => 'Введение в менеджмент', 'ar' => 'مدخل إلى الإدارة'],
            'IOTF-139' => ['en' => 'IoT Fundamentals', 'uz' => 'Buyumlar interneti asoslari', 'ru' => 'Основы интернета вещей', 'ar' => 'أساسيات إنترنت الأشياء'],
            'LOGI-160' => ['en' => 'Logical Programmable Devices and Systems', 'uz' => 'Mantiqiy dasturlanadigan qurilmalar va tizimlar', 'ru' => 'Логические программируемые устройства и системы', 'ar' => 'الأجهزة والأنظمة المنطقية القابلة للبرمجة'],
            'MACR-135' => ['en' => 'Macroeconomics', 'uz' => 'Makroiqtisodiyot', 'ru' => 'Макроэкономика', 'ar' => 'الاقتصاد الكلي'],
            'MARK-110' => ['en' => 'Marketing', 'uz' => 'Marketing asoslari', 'ru' => 'Маркетинг', 'ar' => 'التسويق'],
            'MARK-136' => ['en' => 'Marketing Communications', 'uz' => 'Marketing kommunikatsiyalari', 'ru' => 'Маркетинговые коммуникации', 'ar' => 'اتصالات التسويق'],
            'MARK-137' => ['en' => 'Marketing Research', 'uz' => 'Marketing tadqiqotlari', 'ru' => 'Маркетинговые исследования', 'ar' => 'بحوث التسويق'],
            'MATH-114' => ['en' => 'Mathematical Statistics and Forecasting', 'uz' => 'Matematik statistika va prognozlash', 'ru' => 'Математическая статистика и прогнозирование', 'ar' => 'الإحصاء الرياضي والتنبؤ'],
            'MATH-127' => ['en' => 'Mathematical Bases of Information Processing', 'uz' => 'Axborotni qayta ishlashning matematik asoslari', 'ru' => 'Математические основы обработки информации', 'ar' => 'الأسس الرياضية لمعالجة المعلومات'],
            'META-113' => ['en' => 'Metal Structures', 'uz' => 'Metall konstruksiyalar', 'ru' => 'Металлические конструкции', 'ar' => 'الهياكل والمصنوعات المعدنية'],
            'METH-101' => ['en' => 'Methods and Tools of Information Security', 'uz' => 'Axborot xavfsizligi usullari va vositalari', 'ru' => 'Методы и средства информационной безопасности', 'ar' => 'طرق وأدوات أمن المعلومات'],
            'MICR-105' => ['en' => 'Microeconomics', 'uz' => 'Mikroiqtisodiyot', 'ru' => 'Микроэкономика', 'ar' => 'الاقتصاد الجزئي'],
            'MOBI-102' => ['en' => 'Mobile Devices Programming', 'uz' => 'Mobil qurilmalarni dasturlash', 'ru' => 'Программирование мобильных устройств', 'ar' => 'برمجة الأجهزة المحمولة'],
            'MOBI-128' => ['en' => 'Mobile Applications Creation', 'uz' => 'Mobil ilovalarni yaratish', 'ru' => 'Создание мобильных приложений', 'ar' => 'إنشاء تطبيقات الهاتف المحمول'],
            'MODE-108' => ['en' => 'Modern methods of oil and gas product research', 'uz' => 'Neft va gaz mahsulotlarini tadqiq qilishning zamonaviy usullari', 'ru' => 'Современные методы исследования нефтегазовых продуктов', 'ar' => 'الطرق الحديثة لدراسة منتجات النفط والغاز'],
            'MONE-126' => ['en' => 'Money, Credit and Banks', 'uz' => 'Pul, kredit va banklar', 'ru' => 'Деньги, кредит и банки', 'ar' => 'النقود والائتمان والبنوك'],
            'MULT-142' => ['en' => 'Multimedia Technologies in Education', 'uz' => 'Ta’limda multimedia texnologiyalari', 'ru' => 'Мультимедийные технологии в образовании', 'ar' => 'تقنيات الوسائط المتعددة في التعليم'],
            'NETW-111' => ['en' => 'Network Administration and Information Security', 'uz' => 'Tarmoq administratsiyasi va axborot xavfsizligi', 'ru' => 'Администрирование сетей и информационная безопасность', 'ar' => 'إدارة الشبكات وأمن المعلومات'],
            'OBJE-129' => ['en' => 'Object-Oriented Programming Languages', 'uz' => 'Obyektga yo‘naltirilgan dasturlash tillari', 'ru' => 'Объектно-ориентированные языки программирования', 'ar' => 'لغات البرمجة كائنية التوجه'],
            'OBJE-164' => ['en' => 'Object-Oriented Programming', 'uz' => 'Obyektga yo‘naltirilgan dasturlash', 'ru' => 'Объектно-ориентированное программирование', 'ar' => 'البرمجة كائنية التوجه'],
            'OILA-101' => ['en' => 'Oil and Gas Processing Technology 1, 2', 'uz' => 'Neft va gazni qayta ishlash texnologiyasi 1, 2', 'ru' => 'Технология переработки нефти и газа 1, 2', 'ar' => 'تكنولوجيا معالجة النفط والغاز 1، 2'],
            'OILA-110' => ['en' => 'Oil and Gas Refining Processes', 'uz' => 'Neft va gazni qayta ishlash jarayonlari', 'ru' => 'Процессы переработки нефти и газа', 'ar' => 'عمليات تكرير النفط والغاز'],
            'OPER-111' => ['en' => 'Operations Management', 'uz' => 'Operatsiyalarni boshqarish', 'ru' => 'Операционный менеджмент', 'ar' => 'إدارة العمليات'],
            'ORGA-108' => ['en' => 'Organizational Behavior', 'uz' => 'Tashkiliy xulq-atvor', 'ru' => 'Организационное поведение', 'ar' => 'السلوك التنظيمي'],
            'PAIN-115' => ['en' => 'Paint and Coating Materials Technology', 'uz' => 'Lak-bo‘yoq materiallari texnologiyasi', 'ru' => 'Технология лакокрасочных материалов', 'ar' => 'تكنولوجيا مواد الطلاء والدهانات'],
            'PHYS-107' => ['en' => 'Physicochemical methods for determining food quality', 'uz' => 'Oziq-ovqat sifatini aniqlashning fizik-kimyoviy usullari', 'ru' => 'Физико-химические методы определения качества пищевых продуктов', 'ar' => 'الطرق الفيزيائية الكيميائية لتحديد جودة الأغذية'],
            'POLY-108' => ['en' => 'Polymer Building Materials', 'uz' => 'Polimer qurilish materiallari', 'ru' => 'Полимерные строительные материалы', 'ar' => 'مواد البناء البوليمرية والمشتقة'],
            'POWE-109' => ['en' => 'Power Plants and Substations', 'uz' => 'Elektr stansiyalari va podstansiyalar', 'ru' => 'Электрические станции и подстанции', 'ar' => 'محطات الطاقة والمحطات الفرعية'],
            'PROB-152' => ['en' => 'Probability and Statistics', 'uz' => 'Ehtimollar nazariyasi va statistika', 'ru' => 'Теория вероятностей и статистика', 'ar' => 'الاحتمالات والإحصاء'],
            'PROD-107' => ['en' => 'Production Technology of Aerated Concrete and Foam Concrete Products', 'uz' => 'Gazobeton va ko‘pikbeton mahsulotlarini ishlab chiqarish texnologiyasi', 'ru' => 'Технология производства изделий из газобетона и пенобетона', 'ar' => 'تكنولوجيا إنتاج الخرسانة الخلوية والخرسانة الرغوية'],
            'PROD-112' => ['en' => 'Production Technologies', 'uz' => 'Ishlab chiqarish texnologiyalari', 'ru' => 'Производственные технологии', 'ar' => 'تقنيات الإنتاج'],
            'PROD-115' => ['en' => 'Production Management', 'uz' => 'Ishlab chiqarishni boshqarish', 'ru' => 'Управление производством', 'ar' => 'إدارة الإنتاج'],
            'PROG-136' => ['en' => 'Programming Fundamentals', 'uz' => 'Dasturlash asoslari', 'ru' => 'Основы программирования', 'ar' => 'أساسيات البرمجة'],
            'PROG-144' => ['en' => 'Programming 1, 2', 'uz' => 'Dasturlash 1, 2', 'ru' => 'Программирование 1, 2', 'ar' => 'البرمجة 1، 2'],
            'PROJ-133' => ['en' => 'Project Management', 'uz' => 'Loyihalarni boshqarish', 'ru' => 'Управление проектами', 'ar' => 'إدارة المشاريع'],
            'PUBL-131' => ['en' => 'Public Service in Information Systems', 'uz' => 'Axborot tizimlarida davlat xizmatlari', 'ru' => 'Государственные услуги в информационных системах', 'ar' => 'الخدمات العامة في أنظمة المعلومات'],
            'QUAL-107' => ['en' => 'Quality control of oil and gas products', 'uz' => 'Neft va gaz mahsulotlari sifatini nazorat qilish', 'ru' => 'Контроль качества нефтегазовых продуктов', 'ar' => 'مراقبة جودة منتجات النفط والغاز'],
            'QUAL-109' => ['en' => 'Quality Management', 'uz' => 'Sifat menejmenti', 'ru' => 'Управление качеством', 'ar' => 'إدارة الجودة'],
            'REIN-103' => ['en' => 'Reinforced Concrete and Masonry Structures', 'uz' => 'Temir-beton va tosh konstruksiyalar', 'ru' => 'Железобетонные и каменные конструкции', 'ar' => 'الهياكل الخرسانية المسلحة والحجرية'],
            'REPA-111' => ['en' => 'Repair and Restoration of Architectural Monuments', 'uz' => 'Me’moriy yodgorliklarni ta’mirlash va restavratsiya qilish', 'ru' => 'Ремонт и реставрация архитектурных памятников', 'ar' => 'إصلاح وترميم الآثار التاريخية المعمارية'],
            'RESE-118' => ['en' => 'Research Methods and Skills', 'uz' => 'Tadqiqot usullari va ko‘nikmalari', 'ru' => 'Методы и навыки исследования', 'ar' => 'طرق ومهارات البحث'],
            'RISK-132' => ['en' => 'Risk Management', 'uz' => 'Risklarni boshqarish', 'ru' => 'Управление рисками', 'ar' => 'إدارة المخاطر'],
            'SOCI-100' => ['en' => 'Social Networks and Management', 'uz' => 'Ijtimoiy tarmoqlar va boshqaruv', 'ru' => 'Социальные сети и управление', 'ar' => 'الشبكات الاجتماعية والإدارة'],
            'SOCI-131' => ['en' => 'Social Management', 'uz' => 'Ijtimoiy menejment', 'ru' => 'Социальный менеджмент', 'ar' => 'الإدارة الاجتماعية'],
            'SOFT-112' => ['en' => 'Software Engineering and Object Programming', 'uz' => 'Dasturiy injiniring va obyektli dasturlash', 'ru' => 'Программная инженерия и объектное программирование', 'ar' => 'هندسة البرمجيات والبرمجة الكائنية'],
            'SOFT-161' => ['en' => 'Software Engineering', 'uz' => 'Dasturiy injiniring', 'ru' => 'Программная инженерия', 'ar' => 'هندسة البرمجيات'],
            'SOFT-167' => ['en' => 'Software Testing', 'uz' => 'Dasturiy ta’minotni testlash', 'ru' => 'Тестирование программного обеспечения', 'ar' => 'اختبار البرمجيات'],
            'SOFT-169' => ['en' => 'Software Design', 'uz' => 'Dasturiy ta’minotni loyihalash', 'ru' => 'Проектирование программного обеспечения', 'ar' => 'تصميم البرمجيات'],
            'SOIL-101' => ['en' => 'Soil Mechanics, Bases and Foundations', 'uz' => 'Gruntlar mexanikasi, asoslar va poydevorlar', 'ru' => 'Механика грунтов, основания и фундаменты', 'ar' => 'ميكانيكا التربة وتأسيس المنشآت والأساسات'],
            'STAT-104' => ['en' => 'Statistics', 'uz' => 'Statistika', 'ru' => 'Статистика', 'ar' => 'الإحصاء'],
            'STRA-113' => ['en' => 'Strategic Management', 'uz' => 'Strategik menejment', 'ru' => 'Стратегический менеджмент', 'ar' => 'الإدارة الاستراتيجية'],
            'TAXE-127' => ['en' => 'Taxes and Taxation', 'uz' => 'Soliqlar va soliqqa tortish', 'ru' => 'Налоги и налогообложение', 'ar' => 'الضرائب والجباية'],
            'TEAM-137' => ['en' => 'Team Software Development Technology', 'uz' => 'Jamoaviy dasturiy ta’minot ishlab chiqish texnologiyasi', 'ru' => 'Технология командной разработки программного обеспечения', 'ar' => 'تقنية تطوير البرمجيات ضمن فريق'],
            'TECH-100' => ['en' => 'Technical Condition Assessment of Buildings and Structures', 'uz' => 'Bino va inshootlarning texnik holatini baholash', 'ru' => 'Оценка технического состояния зданий и сооружений', 'ar' => 'تقييم الحالة الفنية للمباني والمنشآت'],
            'TECH-110' => ['en' => 'Technical Means of Automation', 'uz' => 'Avtomatlashtirishning texnik vositalari', 'ru' => 'Технические средства автоматизации', 'ar' => 'الوسائل التقنية للأتمتة'],
            'TECH-111' => ['en' => 'Technology of grain storage and grain products', 'uz' => 'Don va don mahsulotlarini saqlash texnologiyasi', 'ru' => 'Технология хранения зерна и зернопродуктов', 'ar' => 'تكنولوجيا تخزين الحبوب ومنتجاتها'],
            'TECH-114' => ['en' => 'Technological Equipment of Construction Industry', 'uz' => 'Qurilish sanoatining texnologik jihozlari', 'ru' => 'Технологическое оборудование строительной индустрии', 'ar' => 'المعدات التكنولوجية لصناعة البناء'],
            'TECH-141' => ['en' => 'Technical and Software Maintenance of Computer Systems and Networks', 'uz' => 'Kompyuter tizimlari va tarmoqlariga texnik hamda dasturiy xizmat ko‘rsatish', 'ru' => 'Техническое и программное обслуживание компьютерных систем и сетей', 'ar' => 'الصيانة التقنية والبرمجية لأنظمة وشبكات الحاسوب'],
            'THEO-100' => ['en' => 'Theoretical Electrical Engineering', 'uz' => 'Nazariy elektrotexnika', 'ru' => 'Теоретическая электротехника', 'ar' => 'الهندسة الكهربائية النظرية'],
            'TIME-128' => ['en' => 'Time Management', 'uz' => 'Vaqtni boshqarish', 'ru' => 'Тайм-менеджмент', 'ar' => 'إدارة الوقت'],
            'TRAN-106' => ['en' => 'Transportation and Engineering Equipment', 'uz' => 'Transport va muhandislik jihozlari', 'ru' => 'Транспортное и инженерное оборудование', 'ar' => 'النقل والمعدات الهندسية'],
            'TRAN-108' => ['en' => 'Transient Processes', 'uz' => 'O‘tkinchi jarayonlar', 'ru' => 'Переходные процессы', 'ar' => 'العمليات الانتقالية'],
            'TYPO-105' => ['en' => 'Typology of Buildings and Structures', 'uz' => 'Bino va inshootlar tipologiyasi', 'ru' => 'Типология зданий и сооружений', 'ar' => 'تصنيف المباني والمنشآت'],
            'URBA-104' => ['en' => 'Urban Planning and Landscape Design', 'uz' => 'Shaharsozlik va landshaft dizayni', 'ru' => 'Градостроительство и ландшафтное проектирование', 'ar' => 'التخطيط العمراني وتصميم المناظر الطبيعية'],
            'WALL-105' => ['en' => 'Wall Building Materials Technology', 'uz' => 'Devorbop qurilish materiallari texnologiyasi', 'ru' => 'Технология стеновых строительных материалов', 'ar' => 'تكنولوجيا مواد بناء الجدران'],
            'WATE-118' => ['en' => 'Water Treatment Technology and Chemical Control in TPP', 'uz' => 'IESda suv tayyorlash texnologiyasi va kimyoviy nazorat', 'ru' => 'Технология водоподготовки и химический контроль на ТЭС', 'ar' => 'تكنولوجيا معالجة المياه والرقابة الكيميائية في محطات الطاقة الحرارية'],
            'WEBA-103' => ['en' => 'Web Application Development', 'uz' => 'Veb-ilovalarni ishlab chiqish', 'ru' => 'Разработка веб-приложений', 'ar' => 'تطوير تطبيقات الويب'],
            'WEBA-168' => ['en' => 'Web Application Development', 'uz' => 'Veb-ilovalarni ishlab chiqish', 'ru' => 'Разработка веб-приложений', 'ar' => 'تطوير تطبيقات الويب'],
            'WEBP-116' => ['en' => 'Web Programming and Network Databases', 'uz' => 'Veb dasturlash va tarmoq ma’lumotlar bazalari', 'ru' => 'Веб-программирование и сетевые базы данных', 'ar' => 'برمجة الويب وقواعد بيانات الشبكات'],
            'WEBP-163' => ['en' => 'Web Programming Fundamentals', 'uz' => 'Veb dasturlash asoslari', 'ru' => 'Основы веб-программирования', 'ar' => 'أساسيات برمجة الويب'],
            'WEBS-155' => ['en' => 'Web Systems', 'uz' => 'Veb tizimlar', 'ru' => 'Веб-системы', 'ar' => 'أنظمة الويب'],
            'WEBT-126' => ['en' => 'Web Technologies', 'uz' => 'Veb texnologiyalar', 'ru' => 'Веб-технологии', 'ar' => 'تقنيات الويب'],
            'WOOD-112' => ['en' => 'Wooden Structures', 'uz' => 'Yog‘och konstruksiyalar', 'ru' => 'Деревянные конструкции', 'ar' => 'الهياكل الخشبية وأعمال النجارة'],
        ];
    }
};
