import requirementsRaw from "./facultyTechnologyRequirements.cleaned.txt?raw";

export const TECHNOLOGY_FACULTY_ID = "faculty-of-technology";

export const TECHNOLOGY_DEPARTMENT_SLUGS = [
  "oil-gas-refining-technology",
  "food-technology-service",
  "chemical-technology",
  "agricultural-products-storage-oil-fat-technology",
  "oil-gas-engineering-upstream-downstream",
  "metrology-standardization-quality-control",
];

export const technologyDepartmentRouteAliases = {
  "oil-and-gas-refining-technology": "oil-gas-refining-technology",
  "food-technology-and-service": "food-technology-service",
  "oil-and-gas-engineering-upstream-downstream": "oil-gas-engineering-upstream-downstream",
  "metrology-standardization-and-quality-control": "metrology-standardization-quality-control",
};

const sourceDocument = "apps/web/src/data/facultyTechnologyRequirements.cleaned.txt";
const fallback = (text, ar = text) => ({ en: text, uz: text, ru: text, ar });
const webImage = (path) => path.replace(/\\/g, "/").replace(/^.*?public\//, "/");
const normalizeRequirementText = (text) => text.replace(/\\/g, "/");

const requirementsText = normalizeRequirementText(requirementsRaw);

const sliceRequirements = (startMarker, endMarker = null) => {
  const start = requirementsText.indexOf(startMarker);
  if (start === -1) return "";
  const end = endMarker ? requirementsText.indexOf(endMarker, start + startMarker.length) : -1;
  return requirementsText.slice(start, end === -1 ? undefined : end).trim();
};

const facultyRawContent = sliceRequirements("سوف نبدا", "+ معلومات اول قسم وهو");
const rawByDepartment = {
  "oil-gas-refining-technology": sliceRequirements("+ معلومات اول قسم وهو", "القسم الثاني هو Food Technology and Service"),
  "food-technology-service": sliceRequirements("القسم الثاني هو Food Technology and Service", "القسم الثالث هو  Chemical Technology"),
  "chemical-technology": sliceRequirements("القسم الثالث هو  Chemical Technology", "القسم الرابع هو Agricultural Products Storage & Oil-Fat Technology"),
  "agricultural-products-storage-oil-fat-technology": sliceRequirements("القسم الرابع هو Agricultural Products Storage & Oil-Fat Technology", "القسم الخامس هو Department of Oil and Gas Engineering"),
  "oil-gas-engineering-upstream-downstream": sliceRequirements("القسم الخامس هو Department of Oil and Gas Engineering", "والقسم السادس هو Metrology, Standardization, and Quality Control"),
  "metrology-standardization-quality-control": sliceRequirements("والقسم السادس هو Metrology, Standardization, and Quality Control"),
};

const deanImages = {
  adizov: "/assets/img/Dean/Adizov-Rashid-Tokhtayevich.jpg",
  safarov: "/assets/img/Dean/Safarov-Jasur-Alijon-ogli.jpg",
  bozorov: "/assets/img/Dean/Bozorov-Dilmurod-Xolmurodovich.jpg",
};

const existingFallbackImages = {
  adizov: "/assets/img/faculties/dean_adizov.jpg",
  safarov: "/assets/img/faculties/deputy_academic_safarov.jpg",
  bozorov: "/assets/img/faculties/deputy_youth_bozorov.jpg",
};

const oilRefiningImageBase = "/assets/img/departments-Oil and Gas Refining Technology";
const foodImageBase = "/assets/img/departments-Food-Technology-and-Service";
const technologyImageBase = "/assets/img/departments/technology";

const person = ({ name, role, title, reception, phone, email, image, fallbackImage }) => ({
  name,
  role,
  title: title || role,
  reception,
  phone,
  email,
  image,
  fallbackImage,
});

const technologyProgramIds = {
  "60710100|Chemical Engineering": "chemical-engineering",
  "60710200|Biotechnology": "biotechnology",
  "60710300|Printing and Packaging Engineering": "printing-packaging-engineering",
  "60710800|Metrology and Standardization": "metrology-standardization",
  "60810700|Storage and Processing Technology of Agricultural Products": "agricultural-products-storage-processing",
  "60811000|Horticulture and Viticulture": "horticulture-viticulture",
  "60720100|Food Technology": "food-technology",
  "60720500|Gas Processing Technology": "gas-processing-technology",
  "60720600|Oil and Oil-Gas Processing Technology": "oil-gas-processing-technology",
  "60720900|Geology, Exploration and Prospecting of Mineral Deposits": "geology-exploration-mineral-deposits",
  "60721100|Oil and Gas Engineering": "oil-gas-engineering",
  "70710103|Chemical Technology of High-Molecular Compounds (Polymer Production)": "polymer-production-technology",
  "70720101|Technology of Food Production and Processing (Grain Storage and Processing Technology)": "grain-storage-processing-technology",
  "70720101|Technology of Food Production and Processing (Oil Processing Technology)": "oil-processing-technology",
  "70710101|Chemical Technology (Inorganic Substances Chemical Technology)": "inorganic-chemical-technology",
  "70710101|Chemical Technology (Silicate and Refractory Nonmetallic Materials Technology)": "silicate-refractory-materials-technology",
  "70710101|Chemical Technology (Organic Substances Chemical Technology)": "organic-chemical-technology",
  "60721100|Technology of oil and gas refining": "oil-gas-refining-technology-program",
  "60720500|Technology of Deep Gas Processing": "deep-gas-processing-technology",
  "70720600|Technology of oil and gas processing": "oil-gas-processing-master",
  "02.00.08|Chemistry and technology of oil and gas": "oil-gas-chemistry-technology-doctoral",
  "60720100|Food technology": "food-technology",
  "60720300|Technology of wine growing, whisking products and soft drinks": "wine-fermentation-soft-drinks-technology",
  "60720400|Conservation Technology": "food-conservation-technology",
  "70720101|Technology of processing and processing of food products (bakery products)": "bakery-products-technology",
  "70720101|Technology of processing and processing of food products (grain products)": "grain-products-technology",
  "60710100|Chemical technology (chemical technology of inorganic substances)": "inorganic-chemical-technology-bachelor",
  "60710100|Chemical technology (Silicate and Hard-to-Melt Nonmetallic Materials)": "silicate-hard-melting-materials-technology",
  "60710300|Technology of printing and packaging processes": "printing-packaging-engineering",
  "60710100|Chemical Technology (Organic Substances)": "organic-substances-chemical-technology-bachelor",
  "60710100|Chemical Technology (High Molecular Compounds)": "high-molecular-compounds-technology-bachelor",
  "70710101|Chemical technology of inorganic substances": "inorganic-chemical-technology",
  "70710101|Technology of silicate and hardly soluble nonmetallic materials": "silicate-refractory-materials-technology",
  "70710101|Technology of mineral fertilizers": "mineral-fertilizers-technology",
  "70710103|Chemical technology of high molecular weight compounds (technology of polymer production)": "polymer-production-technology",
  "70710101|Chemical technology (production of organic compounds)": "organic-chemical-technology",
  "02.00.11|Chemistry of colloids and membranes": "colloids-membranes-chemistry-doctoral",
  "02.00.13|Technology of inorganic substances and materials based on them": "inorganic-substances-materials-doctoral",
  "02.00.14|Technology of organic substances and materials based on them": "organic-substances-materials-doctoral",
  "02.00.16|Chemical technology, processes and devices of food industry": "food-industry-chemical-technology-doctoral",
  "02.00.17|Technologies and biotechnologies for processing, storage and processing of agricultural and food products": "agricultural-food-products-biotechnology-doctoral",
  "60811300|Technology of storage and processing of agricultural products": "agricultural-products-storage-processing-60811300",
  "60811800|Fruit and viticulture": "fruit-viticulture",
  "60720100|Food technology (oil and oil products)": "food-technology-oil-products",
  "60720200|Technology of fats, essential oils and perfumes cosmetics": "fats-essential-oils-perfume-cosmetics-technology",
  "70720101|Technology of production and processing of food products (oil and oil products)": "oil-fat-products-processing-technology",
  "70720701|Technology of storage and processing of agricultural products": "agricultural-products-storage-processing-master",
  "60721800|Oil and gas works (start-up and development of oil and gas fields)": "oil-gas-field-development",
  "5311900|Oil and gas works (start-up and development of oil and gas fields)": "oil-gas-field-development-5311900",
  "5311900|Start-up and exploitation of oil and gas fields": "oil-gas-fields-exploitation",
  "70721802|The use of machinery and equipment for oil and gas fields": "oil-gas-field-machinery-master",
  "5A311902|The use of machinery and equipment of oil and gas fields": "oil-gas-field-equipment-5a311902",
  "60710800|Metrology and standardization": "metrology-standardization",
  "60711300|Metrology standardization and product quality management": "metrology-quality-management",
  "70710802|Metrologiya, standartlashtirish va sifatni boshqarish": "metrology-standardization-quality-management-master",
};

const program = (code, name, level, note = "") => {
  const id = technologyProgramIds[`${code}|${name}`] || "";
  return {
    code,
    name,
    level,
    note,
    id,
    route: id ? `/programs/${id}` : "",
  };
};

const publication = (title, category = "article") => ({ title, category });

export const facultyTechnology = {
  id: TECHNOLOGY_FACULTY_ID,
  slug: TECHNOLOGY_FACULTY_ID,
  route: "/faculty/faculty-of-technology",
  name: "Faculty of Technology",
  title: fallback("Faculty of Technology", "كلية التكنولوجيا"),
  sourceDocument,
  sourceOfTruth: sourceDocument,
  rawContent: {
    fullRequirements: requirementsText,
    facultySection: facultyRawContent,
  },
  overview: fallback(
    "The faculty has established continuous cooperation between its specialized departments and industrial enterprises. Department branches have been organized within these enterprises, where students visit during their free time to reinforce the theoretical knowledge gained in class through practical experience. In addition, specialists from industrial enterprises are actively involved in the educational process. Specialists from these enterprises directly participate in the classes of graduating students, assess their knowledge, and sign official contracts with them, providing all the necessary conditions for the students to complete their pre-graduation internships at their enterprises. During the internship period, the heads of industrial enterprises ensure the employment of students who demonstrate strong knowledge and potential. The faculty is headed by Associate Professor R.T. Adizov, Ph.D. (Technical Sciences), who has 40 years of experience and whose academic expertise is recognized by foreign higher education institutions as well.",
    "كلية التكنولوجيا"
  ),
  leadership: [
    person({
      name: "Adizov Rashid Tokhtayevich",
      role: "Dean of the Faculty of Technology",
      title: "Associate Professor, PhD in Technical Sciences",
      reception: "Every day 14:00-16:00 (except Monday and Saturday)",
      phone: "+998 93 479 77 65",
      email: "adizov.rashid@mail.ru",
      image: deanImages.adizov,
      fallbackImage: existingFallbackImages.adizov,
    }),
    person({
      name: "Safarov Jasur Alijon o‘g‘li",
      role: "Deputy Dean for Academic Affairs",
      reception: "Every day 14:00-16:00",
      phone: "+998 93 688 56 88",
      email: "jasur.safarov1993@mail.ru",
      image: deanImages.safarov,
      fallbackImage: existingFallbackImages.safarov,
    }),
    person({
      name: "Bozorov Dilmurod Xolmurodovich",
      role: "Deputy Dean for Youth Affairs",
      reception: "Every day 14:00-16:00",
      phone: "+998 90 744 47 97",
      email: "d.bozorov_78@mail.ru",
      image: deanImages.bozorov,
      fallbackImage: existingFallbackImages.bozorov,
    }),
  ],
  imageAssets: [
    { id: "dean-adizov", src: deanImages.adizov, fallback: existingFallbackImages.adizov, alt: "Adizov Rashid Tokhtayevich" },
    { id: "deputy-safarov", src: deanImages.safarov, fallback: existingFallbackImages.safarov, alt: "Safarov Jasur Alijon o‘g‘li" },
    { id: "deputy-bozorov", src: deanImages.bozorov, fallback: existingFallbackImages.bozorov, alt: "Bozorov Dilmurod Xolmurodovich" },
  ],
  bachelorPrograms: [
    program("60710100", "Chemical Engineering", "bachelor"),
    program("60710200", "Biotechnology", "bachelor"),
    program("60710300", "Printing and Packaging Engineering", "bachelor"),
    program("60710800", "Metrology and Standardization", "bachelor"),
    program("60810700", "Storage and Processing Technology of Agricultural Products", "bachelor"),
    program("60811000", "Horticulture and Viticulture", "bachelor"),
    program("60720100", "Food Technology", "bachelor"),
    program("60720500", "Gas Processing Technology", "bachelor"),
    program("60720600", "Oil and Oil-Gas Processing Technology", "bachelor"),
    program("60720900", "Geology, Exploration and Prospecting of Mineral Deposits", "bachelor"),
    program("60721100", "Oil and Gas Engineering", "bachelor"),
  ],
  masterSpecializations: [
    program("70710103", "Chemical Technology of High-Molecular Compounds (Polymer Production)", "master"),
    program("70720101", "Technology of Food Production and Processing (Grain Storage and Processing Technology)", "master"),
    program("70720101", "Technology of Food Production and Processing (Oil Processing Technology)", "master"),
    program("70710101", "Chemical Technology (Inorganic Substances Chemical Technology)", "master"),
    program("70710101", "Chemical Technology (Silicate and Refractory Nonmetallic Materials Technology)", "master"),
    program("70710101", "Chemical Technology (Organic Substances Chemical Technology)", "master"),
  ],
};

const departments = {
  "oil-gas-refining-technology": {
    name: "Oil and Gas Refining Technology",
    title: fallback("Oil and Gas Refining Technology"),
    slug: "oil-gas-refining-technology",
    route: "/department/oil-gas-refining-technology",
    aliases: ["/department/oil-and-gas-refining-technology"],
    sourceLink: "https://old.bstu.uz/kafedra/neft-gazni-qayta-ishlash-texnologiyasi",
    imageFolder: `${oilRefiningImageBase}/`,
    contact: person({
      name: "Ochilov Abduraxim Abdurasulovich",
      role: "Head of Department",
      title: "PhD, associate professor",
      reception: "Dushanba-Juma (14:00-16:00 gacha)",
      phone: "+998 91 411 00 16",
      email: "ochilov82@gmail.ru",
      image: `${oilRefiningImageBase}/Ochilov-Abduraxim-Abdurasulovich.jpg`,
      fallbackImage: `${technologyImageBase}/ochilov-abduraxim-abdurasulovich.jpg`,
    }),
    history: [
      "Since 2001-2002 academic year on the basis of Bukhara Autonomous Okrug and Yesti, the Department of Technologies of Oil and Gas Processing has been organized. The purpose of the creation of the department in this region was to provide qualified personnel to the Bukhara oil refinery, the Mubarak gas refinery, the Gazlineftegaziburization department and other enterprises.",
      "On April 15, 2013, in accordance with decree PP-1954, the Department of Technologies of Oil and Gas Processing and Oil and Gas Business was formed from the merger of the earlier departments.",
      "On July 10, 2019, three departments were established on the basis of the Department of Petroleum and Gas Chemical Industry Technology. From September 13, 2025 to the present, the department has been headed by Ph.D., associate professor A.A. Ochilov.",
    ],
    preparedSpecialists: [
      program("60721100", "Technology of oil and gas refining", "bachelor"),
      program("60720500", "Technology of Deep Gas Processing", "bachelor"),
      program("70720600", "Technology of oil and gas processing", "master"),
      program("02.00.08", "Chemistry and technology of oil and gas", "doctoral"),
    ],
    subjects: {
      bachelor: [
        "Introduction to Specialization",
        "Oil and Gas Processing Technology 1,2",
        "Equipment and equipment for oil and gas processing 1,2",
        "Design of enterprises of the oil and gas processing industry",
        "General Chemical Technology",
        "Synthesis and Technology of Monomers from Gas and Gas Condensate",
        "Chemistry and Technology of Fuels and Oils",
        "Disposal of oil and gas processing waste",
        "Quality control of oil and gas products",
        "Modern methods of oil and gas product research",
        "Physics and Chemistry of Natural Gas and Gas Condensates 1,2",
        "Hydrocarbon Gas Processing Technology 1,2",
        "Technology of Natural Gas and Gas Condensate Processing",
        "Chemistry and Technology of Polymer Processing",
        "Synthesis and Technology of Monomers Based on Gases and Gas Condensate",
        "Protection of metals from corrosion",
        "Oil and Gas Refining Processes",
        "Production of liquid hydrocarbons from gas using GTL technology in Uzbekistan",
        "Petroleum-Gas Chemistry and Physics",
        "Equipment and equipment of oil and gas refineries",
        "Chemistry and Technology of Synthetic and Biofuels Production",
        "Deep Oil Refining Technology",
        "Pyrolysis of Hydrocarbon Feedstock",
        "Physics and Chemistry of Hydrocarbon Gases",
        "Operation of Oil Bases and Gas Stations",
        "Energy Saving Technologies in Oil and Gas Refining Industry",
        "Training on the processes of the oil and gas refining industry",
        "Landings used in the petrochemical industry",
        "Additional resources in the oil and gas chemical industry",
        "Inorganic sorbents of oil and gas refining",
        "Catalyst in the Gas Chemical Industry",
        "Technology of Synthesis Gas Production",
        "Gas Supply Systems",
        "Use of gas distribution and disposal points",
        "Process training of the gas chemical industry",
      ],
      master: [
        "Methodology of scientific research",
        "Technology of deep processing of oil and gas 1,2",
        "Corrosion protection of oil and gas refining equipment",
        "Improvement and design of oil and gas processing enterprises",
        "Methods of teaching special disciplines",
        "Research work and preparation of master's dissertation",
        "Scientific and pedagogical work",
        "Modern methods of physical and chemical analysis",
        "Industrial technologies and innovations",
        "Experimental planning",
        "Chemistry of oil and gas refining products",
        "Chemistry and technology of obtaining additives for fuels and oils",
        "Chemistry of production of alternative and synthetic mature fuels",
        "Chemistry and technology of natural gas-based syntheses",
      ],
    },
    staff: [
      person({ name: "Ochilov Abdurasulovich", role: "Head of the department", image: `${oilRefiningImageBase}/Ochilov-Abduraxim-Abdurasulovich.jpg`, fallbackImage: `${technologyImageBase}/ochilov-abduraxim-abdurasulovich.jpg` }),
      person({ name: "Maxmudov Muxtor Jamolovich", role: "DSc, professor", image: `${oilRefiningImageBase}/Maxmudov-Muxtor-Jamolovich.jpg` }),
      person({ name: "Hayitov Ruslan Rustamjonovich", role: "DSc, professor", image: `${oilRefiningImageBase}/Hayitov Ruslan Rustamjonovich.jpg` }),
      person({ name: "Bozorov G‘ayrat Rashidovich", role: "DSc, professor", image: `${oilRefiningImageBase}/Bozorov G‘ayrat Rashidovich.jpg` }),
      person({ name: "Xo‘jaqulov Aziz Fayzullaevich", role: "PhD, dotsent", image: `${oilRefiningImageBase}/Xo‘jaqulov Aziz Fayzullaevich.jpg`, fallbackImage: "/assets/img/departments/xojaqulov.jpg" }),
      person({ name: "Murodov Malik Negmurodovich", role: "t.f.n., dotsent", image: `${oilRefiningImageBase}/Murodov Malik Negmurodovich.jpg` }),
      person({ name: "Safarov Baxri Djumaevich", role: "t.f.n., dotsent", image: `${oilRefiningImageBase}/Safarov Baxri Djumaevich.jpg` }),
      person({ name: "Tsukanov Maksim Nikolayevich", role: "PhD, dotsent", image: `${oilRefiningImageBase}/Tsukanov Maksim Nikolayevich.jpg` }),
    ],
    publications: {
      conferencePapers: [
        publication("J.A. Safarov, R.R. Hayitov. The S&P 500 has been hit hard by the S&P 500 Index. \"The Politics and Politics of Nigeria...\" Proceedings of the National Conference-Symposium, November 25, 2021, pp. 165-167.", "conference"),
        publication("Ж.А. Сафаров, Р.Р. Ҳайитов. Ишлатилган мотор мойларининг таркибини аниқлаш. В-Халқаро конференция-симпозиум, 25 ноябрь 2021 й., 255-258 б.", "conference"),
        publication("Ж.А. Сафаров, Р.Р. Ҳайитов. Ишлатилган мотор мойларини тозалаш усулини танлаш. В-Халқаро конференция-симпозиум, 25 ноябрь 2021 й., 258-261 б.", "conference"),
        publication("Ж.А. Сафаров, К.Ш. Ҳотамов. Юқори сифатли дизель ёқилғиларини ишлаб чиқариш жараёнларининг замонавий ҳолати. Тошкент, 2021.", "conference"),
        publication("О.Б. Ахмедова, З.Н. Акрамова. Газни тайёрлаш жараёнида паст ҳароратли сепараторни тадқиқ қилиш. Бухоро, 20-22 октябрь 2021 й., 326-327 б.", "conference"),
        publication("O.B. Akhmedova, Sh. Akhmedova. Gazlarni nordon komponentlardan tozalash uchun samarali absorbent compositionsini ishlab chikish. Bukhoro, October 20-22, 2021, 328-329 p.", "conference"),
        publication("B.B. Toirov, A.A. Alimov. The relevance of production of synthetic petroleum feedstock from coal crude. Tashkent, 2022, pp. 135-137.", "conference"),
        publication("N.I. Bakhramov, O.B. Akhmedova, R.R. Hayitov. Investigation of the composition of granulated active charcoal for purification of alkanolamines. Retrieved November 25, 2021, pp. 192-194.", "conference"),
        publication("O.B. Akhmedova, Z.Z. Rakhimov. Technique for obtaining methyldiethanolamine, which is applied in the treatment of gases. Retrieved November 25, 2021, pp. 167-170.", "conference"),
      ],
      scopusWebOfScience: [
        publication("Kayum Jumaev, Baxodir Tursunov. Technology for Obtaining Fuel Briquettes from Oil Waste. IOP Conference Series: Earth and Environmental Science, Krasnoyarsk, Russia, 16-18 June 2022.", "scopus"),
      ],
      textbooksManuals: [
        publication("M.Zh. Makhmudov and others. Modern methods of physicochemical analysis. 2024.", "textbook"),
        publication("E.R. Panoyev and others. Catalytic processes and catalysts for petrochemical industry. 2025 year.", "textbook"),
        publication("B.J Tursunov and others. Chemistry and physics of petroleum. 2025 year.", "textbook"),
        publication("M.Q. Turakulova and others. Research Methodology. 2025 year.", "textbook"),
        publication("S.F. Fozilov and others. Methods of physical and chemical analysis of oil and gas products. 2025 year.", "textbook"),
      ],
      monographs: [
        publication("Small biogas plants designed for the population and farms. Bukhara, 2021.", "monograph"),
        publication("Activated Charcoal for Organic Feedstock Gas Processing Plants. Bukhara, 2021.", "monograph"),
        publication("Technology for Obtaining Polymethacrylate-Based Additives for Fuels and Oils. Bukhara, 2020.", "monograph"),
        publication("Obtaining effective solutions based on drilling muds. Bukhara, 2020.", "monograph"),
        publication("Motor Gasolines and Ways to Improve Their Sustainability. Tashkent, 2020.", "monograph"),
      ],
    },
    research: [
      "Laboratory modernization with JSC Uzbekneftegaz, CISTU, Bukhara Oil Refinery LLC, and Shurtan Gas Chemical Complex.",
      "Negotiations with Sharif University of Technology for 19 laboratory equipment types worth 186,000 USD.",
      "Scientific council DSc.03/28.02.2022.T.101.01 supports academic degrees in chemistry and technology of oil and gas and colloid and membrane chemistry.",
    ],
    cooperation: [
      "Baku Higher Oil School joint master's education program connected to Uzbekneftegaz JSC and SOCAR cooperation.",
      "Vilnius Gediminas Technical University internship through Erasmus+ UzMedEn.",
      "Atyrau Oil and Gas University named after S. Utebaev.",
      "Ufa State Oil Technical University.",
      "South Kazakhstan University named after M. Auezov.",
      "Hebei Professional University of Technology and Engineering, China.",
    ],
  },
  "food-technology-service": {
    name: "Food Technology and Service",
    title: fallback("Food Technology and Service"),
    slug: "food-technology-service",
    route: "/department/food-technology-service",
    aliases: ["/department/food-technology-and-service"],
    sourceLink: "https://old.bstu.uz/kafedra/oziq-ovqat-texnologiyasi",
    imageFolder: `${foodImageBase}/`,
    contact: person({
      name: "Qurbonov Murod Tashpulatovich",
      role: "Head of Department",
      reception: "Dushanba-Shanba (15:00-17:00)",
      phone: "+998 90 299 85 48",
      email: "kurbanov.m@rambler.ru",
    }),
    history: [
      "In accordance with decree No. 6 of 1980, the department Technology of bread, pasta and confectionery products was organized.",
      "Since August 28, 2017, according to the new structure of the institute, Food Technology was renamed into the Department of 5321000-Food Technology (by branches).",
      "Earlier educational areas were led by Vosiev M.G., Mokhnacheva A.I., I.B. Isabaev, Tındybekov O.T., Lavrinovich Yu.I., Ismatov N.A., Boboev S.D., Khaitov R.A., Adizov R.T., Majidov Q.X., Egamberdiev N.B., Makhmadaliev B.D., Sharifulina T.A., Salomov H.T., Salomov B.H., and Quliev N.Sh.",
    ],
    staff: [
      person({ name: "Atamuradova Tamara Ivanovna", role: "Candidate of the Technical Science Associate Professor", image: `${technologyImageBase}/atamuradova-tamara-ivanovna.jpg` }),
      person({ name: "Ergasheva Khusrabo Bobonazarovna", role: "Candidate of Technical Sciences, Associate Professor", image: `${technologyImageBase}/ergasheva-khusrabo-bobonazarovna.jpg` }),
      person({ name: "Khaydarzoda Lolitta Negmatovna", role: "Candidate of the technical sciences, associate professor", image: `${technologyImageBase}/khaydarzoda-lolitta-negmatovna.jpg` }),
      person({ name: "Khuzhakulova Nilufar Fayzullayevna", role: "Candidate of the technical sciences, associate professor (PhD)", image: `${technologyImageBase}/khuzhakulova-nilufar-fayzullayevna.jpg` }),
      person({ name: "Yuldasheva Shabon Jumaevna", role: "Senior teacher", image: `${technologyImageBase}/yuldasheva-shabon-jumaevna.jpg` }),
      person({ name: "Ismatova Shakhnoza Nusratillonovna", role: "Candidate of technical sciences, associate professor (PhD)", image: `${technologyImageBase}/ismatova-shakhnoza-nusratillonovna.jpg` }),
      person({ name: "Amonov Bobur Nematovich", role: "Assistant" }),
      person({ name: "Muzafarova Hall Mukhinovna", role: "Assistant" }),
      person({ name: "Khamroyev Jonibek Sadilloyevich", role: "Head of the Cabinet", image: `${technologyImageBase}/xamroyev-jonibek-sadilloyevich.jpg` }),
    ],
    preparedSpecialists: [
      program("60720100", "Food technology", "bachelor"),
      program("60720300", "Technology of wine growing, whisking products and soft drinks", "bachelor"),
      program("60720400", "Conservation Technology", "bachelor"),
      program("70720101", "Technology of processing and processing of food products (bakery products)", "master"),
      program("70720101", "Technology of processing and processing of food products (grain products)", "master"),
    ],
    subjects: {
      bachelor: [
        "Fundamentals of modern professional technology",
        "The composition and properties of plant raw materials",
        "Food biochemistry",
        "Food commodity science",
        "Food examination",
        "Food raw materials and materials commodity science",
        "Food microbiology",
        "Physicochemical methods of determining the quality of food products",
        "Food Research Methods",
        "Raw materials and nutritional additives in the production of bread, pasta and confectionery products",
        "Food Quality Assessment",
        "Bakery, pasta and confectionery equipment",
        "Technology of Pasta Products",
        "Technology of production of confectionery products",
        "Flour and Technologies of Production",
        "Equipment of grain processing enterprises",
        "Technology of storage of grain and grain products",
        "Examination of bread, pasta and confectionery products",
        "Confectionery Products Technology",
        "Bread Biochemistry",
        "Technical and chemical control of bread, pasta and confectionery products",
        "Feed production technology in Omixta",
        "Examination of Grain and Grain Products",
        "Elevator and Warehouse",
        "Basics of financing industrial enterprises",
      ],
      master: [
        "Grain Biochemistry",
        "Innovations in the technology of production of confectionery, bread and pasta products",
        "Scientific basis for improving the efficiency and competitiveness of food production from vegetable raw materials",
        "Ventilation and pneumatic transport devices",
        "Scientific and pedagogical work",
        "Research work and preparation of a master's thesis",
        "Current trends in technology development in the food industry",
        "Use of biotechnology advances in agricultural processing",
        "Scientific Foundations of Un-Baking Technology",
        "Seed processing",
        "The Elevator-Warehouse Industry and Grain Drying",
        "Scientific practice (gaining experience)",
      ],
    },
    activities: [
      "HACCP system training organized by the Association of Food Industry of Uzbekistan, Bukhara Engineering and Technological Institute and GIZ.",
      "Cultural and educational event for the 580th anniversary of Alisher Navoi with senior teacher Sh.J. Yuldasheva and students.",
      "Experience process at JSC Kogondon Products with graduate students, Associate Professor Ergasheva Kh.B. and senior teacher Yuldasheva Sh.J.",
      "N.R. Djuraeva won the Inventive Woman-2022 nomination The Best Invention and Useful Model.",
      "Holiday organized with children of the House of Muruvvat using national adras fabric.",
    ],
    publications: {
      monographs: [
        publication("Kh.B.Ergasheva, Sh.J.Yuldasheva. Technological properties of the wheat of Uzbekistan.", "monograph"),
        publication("Kh.B.Ergasheva, Sh.J.Yuldasheva. Rations of feeding agricultural animals.", "monograph"),
        publication("Kh.B.Ergasheva, Sh.J.Yuldasheva, Sh.N.Ismatova. Research of the process of storing kombikorov in the conditions of Uzbekistan.", "monograph"),
      ],
      textbooksManuals: [
        publication("S.Ravshanov, N.A.Ismatov, Sh.J.Yuldasheva. Modern technologies of flour and oat production.", "textbook"),
        publication("Kh.B.Ergasheva, Sh.J.Yuldasheva, G.Z.Djakhangirova, M.T.Kurbanov. Biochemistry of the Grain.", "textbook"),
        publication("H.B.Ergasheva, M.B. Kamolova. Professional ethics and etiquette. Bukhara, 2020.", "textbook"),
        publication("Kh.B.Ergasheva. Technology of feed production in Omix. Bukhara, 2019.", "textbook"),
        publication("N.A.Ismatov, S.D.Boboev, Sh.Zh.Yuldasheva. Aspiration and ventilation devices.", "textbook"),
      ],
      articles: [
        publication("Ergasheva H.B. Research of Change in Humidity of Local and Other Varieties of Soya Seeds at Various Storage Modes. Annals of R.S.C.B., 2021."),
        publication("Ergasheva H.B. The Effect Of Drinking And Activated Water On Field Scales Of Wheat Grains Grown In Arid Climatic Conditions. European Journal of Molecular & Clinical Medicine, 2020."),
        publication("Amanov B.N. Influence of Products from Tomato Press on The Efficiency of The Technological Process and The Quality of Rye Bread. European Journal of Life Safety and Stability, 2021."),
        publication("Amanov B.N. Applicatios of Natural Additives - Acidiments and Probiotic Bacterial Preparations for Prevention of Rye Bread Cretal Disease. Natural Volatiles and Essential Oils, 2021."),
        publication("Джураева Н.Р. Влияние термообработки на микробную контаминацию эмулсионных жиромучных композитных смесей. Развитие науки и технологий, 2021."),
        publication("Ismatova Sh.N. Justification of the expediency of using sprouted quinoa grain as part of mixed feeds for birds. International Journal of Mechanical Engineering, 2021."),
        publication("Ismatova Sh.N Prospects of the use of quinoa and amaranth for expanding of food reserve of poultry farming. Austrian journal of technical and natural sciences, 2020."),
        publication("Исматова Ш.Н. Изменение химического состава комбикормов при хранении. Universum: Технические науки, 2019."),
        publication("Исматова Ш.Н. Алтернативные источники сыря для производства комбикормовой продукции. Universum: Технические науки, 2019."),
        publication("Xo`jaqulova N.F. Quality and physical and chemical characteristics of local wheat grain kinds. Austrian Journal of Technical and Natural Sciences, 2019."),
        publication("Xo`jaqulova N.F. Влияние гидротермической обработки на биохимические свойства зерна пшеницы. UNIVERSUM: Технические науки, 2020."),
        publication("Xo`jaqulova N.F. Assessment of grade and biochemical composition of Chillaki wheat grain, grown in salted fields. TEST Engineering of Management, 2020."),
        publication("Kh.B.Ergasheva. Study of the influence of soil composition on the yield and quality indicators of wheat grain. Texas Journal of Agriculture and Biological Sciences."),
        publication("B.N. Amanov. Methods Of Application Of Probiotic Bacterial Preparations In The Production Of Rye Bread. Natural Volatiles & Essential Oils, 2021."),
        publication("B.N. Amanov. Prospects for Using Tomato Processing Products in the Production of Rye Bread. Annals of R.S.C.B., 2021."),
        publication("B.N. Amanov. Methods Of Application Of Probiotic Bacterial Preparations In The Production Of Rye Bread. Natural Volatiles and Essential Oils, 2021."),
        publication("L.N. Khaidar-Zade. Application of pumpkin flour in the production of bakery products. Annals of R.S.B., 2022."),
        publication("S.K.Jabborova. Priority areas for improving the range of confectionery. European Sciences Review, 2019."),
        publication("S.K.Jabborova. Analysis of food value of non-traditional sugar substitutes for flour confectionery goods. Asian Journal of Multidimensional Research, 2020."),
        publication("S.K.Jabborova. Application of products of processing mulberries and roots of sugar beet in the production of cupcakes. Journal of Critical Reviews, 2020."),
        publication("S.K.Jabborova, I.B.Isabaev, I.Sh. Sadikov. Methods to prevent silken powder collapsing and clushing during storage. Middle European scientific bulletin, 2020."),
        publication("S.K.Jabborova. Use of Silk Berries and Sugar Beet Roots in the Production of Muffins. International Journal of Innovative Research in Science, Engineering and Technology, 2021."),
        publication("S.K.Jabborova. Silk Berries Beet Roots in The Production of Muffins. Texas Journal of Multidisciplinary Studies, 2021."),
        publication("Курбонов М.Т. Improvement of the design of mobile equipment for post-harvest processing of agricultural crops."),
        publication("Djuraeva N.R. Method for rational use of botanical oil content in wheat germ product. Asian Journal of Multidimensional Research, 2021."),
      ],
    },
    research: [
      "GIZ Vocational education in Central Asia-I program equipped five modern laboratory units.",
      "OUWOW wine technology project with University of Coimbra, Portugal, funded for 200,000 euros.",
      "Practical project PZ-2019062124 Creating technology for the production of mass food products using natural decontaminations, funding 400 mln UZS.",
      "Planned 2023-2024 project Development of technology for the production of functionally oriented flour, oats and bakery products, funding 1.740 billion soums.",
      "Commercial contract with Oltin Ear - Hot Bread LLC for new rye bread recipes and technologies.",
      "Research by Djuraeva N.R. on vegetable and oil mixtures.",
      "Research by Muzafarova H.M. on flour confectionery for heroditic nutrition.",
      "Research by Ismatova Sh.N. on non-traditional means in feed.",
    ],
    cooperation: [
      "Dresden State Technical University, Germany.",
      "Moscow State University of Food Production, Russia.",
      "Tajikistan State Technical University.",
      "Osh State Technical University, Kyrgyzstan.",
      "Mogilev State University of Food and Chemical Technologies, Belarus.",
      "Latvian University of Natural Sciences and Technology, Latvia.",
    ],
    jointPrograms: [
      "Moscow State University of Food Production (MGUPP), Russian Federation.",
      "Mogilyov State University of Food and Chemical Technologies, Republic of Belarus.",
    ],
    prospectivePlans: [],
  },
  "chemical-technology": {
    name: "Chemical Technology",
    title: fallback("Chemical Technology"),
    slug: "chemical-technology",
    route: "/department/chemical-technology",
    aliases: [],
    sourceLink: "https://old.bstu.uz/kafedra/kimyo-texnologiyasi",
    contact: person({
      name: "Axmedov Voxid Nizomovich",
      role: "Head of Department",
      reception: "Dushanba-Juma (14:00-16:00 gacha)",
      phone: "+998 90 511 59 58",
      email: "vohid7@mail.ru",
      image: `${technologyImageBase}/akhmedov-voxid-nizomovich.jpg`,
    }),
    history: [
      "The department trains personnel in 60710100 Chemical technology, 60710300 Technology of printing and packaging processes, 70710100 Chemical technology of high-molecular compounds, and 70710101 Chemical technology.",
      "In these areas work 45 professors and teaching staff, including 4 professors, 24 PhD associate professors, with scientific potential of 60%.",
      "The department has 2 foreign language languages and 47 taught subjects. It trains 2 doctoral students, 28 basic doctoral students and 4 masters.",
    ],
    staff: [
      person({ name: "Akhmedov Voksi Nizomovich", role: "Head of the department", image: `${technologyImageBase}/akhmedov-voxid-nizomovich.jpg` }),
      person({ name: "Makhmudov Rafiq Amonovich", role: "Doctor of Technical Sciences, Professor", image: `${technologyImageBase}/makhmudov-rafiq-amonovich.jpg` }),
      person({ name: "Temirova Matlab Ibodovna", role: "Doctor of Technical Sciences, Professor", image: `${technologyImageBase}/temirova-matlab-ibodovna.jpg` }),
      person({ name: "Haydarov Akhtam Amonovich", role: "Doctor of Technical Sciences, Professor", image: `${technologyImageBase}/haydarov-akhtam-amonovich.jpg` }),
      person({ name: "Olimov Babir Bahodir ugly", role: "PhD, associate professor", image: `${technologyImageBase}/olimov-bobir-bahodir-ogli.jpg` }),
      person({ name: "Panoyev Nadir Shavkatovich", role: "PhD, associate professor", image: `${technologyImageBase}/panoyev-nadir-shavkatovich.jpg` }),
      person({ name: "Sadikova Muxayyo Murodovna", role: "PhD, associate professor", image: `${technologyImageBase}/sadikova-muxayyo-murodovna.jpg` }),
      person({ name: "Sharipov Begmurod Sharopovich", role: "PhD, dotsent" }),
      person({ name: "Umarov Bobur Nosir o'gli", role: "PhD, dotsent", image: `${technologyImageBase}/umarov-bobur-nosir-ogli.jpg` }),
      person({ name: "Khuzhakulova Dilbar Jorakulovna", role: "PhD, associate professor" }),
      person({ name: "Narzullaeva Aziza Murodillayevna", role: "PhD, dotsent" }),
      person({ name: "Voxidov Erkin Aliyevich", role: "PhD, dotsent" }),
      person({ name: "Jo‘raeva Laylo Raxmatillaevna", role: "Assistent", image: `${technologyImageBase}/joraeva-laylo-raxmatillaevna.jpg` }),
      person({ name: "Sharipova Nasiba O‘ktamovna", role: "Assistent" }),
      person({ name: "Raxmatov Marat Salimovich", role: "Assistent" }),
      person({ name: "Sadikova Mashhura Idilloevna", role: "Assistent" }),
      person({ name: "G‘afurova Gulnoz Alixonovna", role: "Assistent", image: `${technologyImageBase}/gafurova-gulnoz-alixonovna.jpg` }),
      person({ name: "Jumaev Jabbor Hamroqulovich", role: "Assistent" }),
      person({ name: "Ikromov Ulugbek Gafur oglu", role: "Teacher, trainee" }),
      person({ name: "Kurbonova Salima Shukhratovna", role: "Teacher trainee" }),
    ],
    preparedSpecialists: [
      program("60710100", "Chemical technology (chemical technology of inorganic substances)", "bachelor"),
      program("60710100", "Chemical technology (Silicate and Hard-to-Melt Nonmetallic Materials)", "bachelor"),
      program("60710300", "Technology of printing and packaging processes", "bachelor"),
      program("60710100", "Chemical Technology (Organic Substances)", "bachelor"),
      program("60710100", "Chemical Technology (High Molecular Compounds)", "bachelor"),
      program("70710101", "Chemical technology of inorganic substances", "master"),
      program("70710101", "Technology of silicate and hardly soluble nonmetallic materials", "master"),
      program("70710101", "Technology of mineral fertilizers", "master"),
      program("70710103", "Chemical technology of high molecular weight compounds (technology of polymer production)", "master"),
      program("70710101", "Chemical technology (production of organic compounds)", "master"),
      program("02.00.11", "Chemistry of colloids and membranes", "phd"),
      program("02.00.13", "Technology of inorganic substances and materials based on them", "phd"),
      program("02.00.14", "Technology of organic substances and materials based on them", "phd"),
      program("02.00.16", "Chemical technology, processes and devices of food industry", "phd"),
      program("02.00.17", "Technologies and biotechnologies for processing, storage and processing of agricultural and food products", "phd"),
    ],
    subjects: {
      bachelor: [
        "Fundamentals of Construction of Manufacturing Enterprises",
        "Bonded nitrogen production technology",
        "Ammonium nitrate production technology",
        "Modern methods of physicochemical analysis",
        "Chemical technology of inorganic substances",
        "Enterprise equipment",
        "Thermal Processes and Devices in the Production of Silicate Materials",
        "Fast Click Methods Technology",
        "General Technology of Silicates",
        "Prepress Technologies and Equipment",
        "Pulp and papermaking technology",
        "Technology of printing materials",
        "Packaging Process Technologies and Equipment",
        "Technology of silicate materials",
        "Fundamentals of organic synthesis",
        "Material hunos candy",
        "Synthesis of organic matter",
        "Organic Synthesis Equipment",
        "Waste-free technologies in organic synthesis",
        "Chemistry and technology of organic substances",
        "Basics of Financing Organic Synthesis Enterprises",
        "Synthetic Detergent Production Technology",
        "Equipment for the production of synthetic detergents",
        "Methods for the synthesis of monomers",
        "Chemistry and Physics of High Molecular Compounds",
        "Technology of coating-forming polymers",
        "Classification of polymer materials and their fields of application",
        "Technology of production of high molecular weight compounds",
        "Chemistry",
        "Chemistry (general and inorganic chemistry, analytical chemistry, physical-colloid chemistry)",
        "Analytical and physical-colloid chemistry",
        "Organic cumin",
        "Construction chemistry",
        "Organic and physical chemistry in construction",
        "Physico-colloid chemistry",
        "Physical chemistry",
      ],
      master: [
        "Technological processes in the production of silicate materials",
        "Theory and technological calculations of the production of mineral fertilizers",
        "Theory and Technological Accounts of the Production of Inorganic Substances",
        "Theory and technological calculations of the production of synthesized gases",
        "Theory and technological calculations of bonded nitrogen production",
        "Chemical technology of mineral fertilizers / Chemical technology of potash salts",
        "Chemistry and Technology of Element Organic Compounds",
        "Adjustment of structure and properties in the manufacturing process of high-molecular compounds",
        "Theoretical foundations of chemistry of high molecular weight compounds",
        "Chemistry and technology of methane-based syntheses",
        "Chemical theoretical foundations of coating-forming polymers",
        "Technology of organic substances and materials based on them",
        "Catalytic processes in the technology of obtaining organic products",
        "Fundamentals of Physics and Mechanics of High Molecular Compounds",
      ],
    },
    publications: {
      textbooksManuals: [
        publication("V.N.Akhmedov, Z.Kh.Rayimov, G.A.Gafurova. Terephthalic acid derivatives. Monograph, Bukhara-2022.", "monograph"),
        publication("Nurilloyev Zafar Ismatilloyevich, Asrayev Zafar Rizakulovich, Khojiyev Azizjon Kholmurodovich. Problems of general and inorganic chemistry and methods of their solution. Electronic textbook. DGU No. 40483.", "electronic-textbook"),
        publication("Makhmudov Rafiq Amonovich, Shukrullaev Javohir Aibek ugli. Modern methods of physical and chemical analysis. DGU No. 23886.", "textbook"),
        publication("R.A.Makhmudov, Ch.K.Khayrullayev, S.A.Niyozov, M.F.Haydarova, Z.M. Kamolova. Theory and Technological Accounts of Bonded Nitrogen Production. Textbook, 2023.", "textbook"),
        publication("R.A.Makhmudov, Z.M. Kamolova, S.A.Niyozov. Technology of Bonded Nitrogen and Nitrogen Fertilizers. Monograph, 2024.", "monograph"),
        publication("Niyozova N.R., Khuzhakulov K.R. Modification and application of synthetic oils in leather industry. Monograph, 2023.", "monograph"),
        publication("Sadirova S.N., Temirova M.I. Effective technological approach in processing Karakul skins. Monograph, 2023.", "monograph"),
        publication("Khaidarov A.A. Полимеры на основе хитина и хитозана. Монография. Бухара-2023.", "monograph"),
        publication("Ostonov F.I., Akhmedov V.N., Fayzullaev N.I., Dzhuraeva L.R., Olimov B.B. Chemistry and technology of polymers. Textbook, 2025.", "textbook"),
        publication("E.Kh.Atoev. Chemistry of elements textbook. Order No. 55 of 04 March 2024.", "textbook"),
      ],
    },
    research: [
      "02.00.11 Chemistry of colloids and membranes: activated coal from domestic raw materials, sorption purification of water, organic metals of established properties.",
      "02.00.13 Technology of inorganic substances and materials: hybrid compounds, low-release nitrogen fertilizers, waste from mineral salts.",
      "02.00.14 Technology of organic substances and materials: hydroxybenzoic acids, amino acids, imidazole fragments, bitumen emulsions.",
      "02.00.16 Chemistry technology and processes/devices of food production: drying process acceleration and alkaline neutralization equipment.",
      "02.00.17 Technologies and biotechnologies for agricultural and food products: high-performance adsorbents in vegetable oil bleaching.",
    ],
    cooperation: [
      "South Kazakhstan State University.",
      "Volgograd Medical University.",
      "Saratov State University.",
      "Joint program with the University of South Kazakhstan named after M. Auezova opened service educational areas in 2019-2021.",
    ],
    news: [],
  },
  "agricultural-products-storage-oil-fat-technology": {
    name: "Agricultural Products Storage & Oil-Fat Technology",
    title: fallback("Agricultural Products Storage & Oil-Fat Technology"),
    slug: "agricultural-products-storage-oil-fat-technology",
    route: "/department/agricultural-products-storage-oil-fat-technology",
    aliases: [],
    sourceLink: "https://old.bstu.uz/kafedra/qishloq-xo-jalik-maxsulotlarini-saqlash-qayta-ishlash-va-yog-moy-texnologiyasi",
    contact: person({
      name: "Majidova Nargiza Kaxramonovna",
      role: "Head of Department",
      title: "Doctor of Technical Sciences, associate professor",
      reception: "Dushanba-Juma (14:00-16:00 gacha)",
      phone: "+998 97 305 95 59",
      email: "nargiz-1234n@mail.ru",
      image: `${technologyImageBase}/majidova-nargiza-kaxramonovna.jpg`,
    }),
    history: [
      "On the basis of the newly created structure of the institute, the department started its work in August 2022 under the name Storage, processing and oil technology of agricultural products, separated from Food technology.",
      "There are 12 professors and teachers at the department, including 2 doctors of science, 2 candidates of science associate professor, 4 doctors of science (PhD), 2 assistants, and 1 trainee, with scientific potential of 78%.",
    ],
    staff: [
      person({ name: "Majidova Nargiza Kakhramonovna", role: "Head of the department, Doctor of Technical Sciences, associate professor", image: `${technologyImageBase}/majidova-nargiza-kaxramonovna.jpg` }),
      person({ name: "Majidov Qakhramon Khalimovich", role: "Doctor of Technical Sciences, professor", image: `${technologyImageBase}/majidov-qakhramon-khalimovich.jpg` }),
      person({ name: "Ashurov Furkat Bakhromovich", role: "Candidate of the technical science, associate professor", image: `${technologyImageBase}/ashurov-furkat-bakhromovich.jpg` }),
      person({ name: "Sabirova Nargiza Nusratovna", role: "PhD, dotsent", image: `${technologyImageBase}/sabirova-nargiza-nusratovna.jpg` }),
      person({ name: "Bozorov Dilmurod Kholmurodovich", role: "PhD, associate professor", image: `${technologyImageBase}/bozorov-dilmurod-kholmurodovich.jpg` }),
      person({ name: "Oltiev Azim To`yqulovich", role: "PhD, dotsent", image: `${technologyImageBase}/oltiev-azim-toyqulovich.jpg` }),
      person({ name: "Fayzullaev Asqar Rajabboevich", role: "Assistant", image: `${technologyImageBase}/fayzullaev-asqar-rajabboevich.jpg` }),
      person({ name: "Mirzaeva Shokhista Usmonovna", role: "PhD, Senior Lecturer", image: `${technologyImageBase}/mirzaeva-shoxista-usmonovna.jpg` }),
      person({ name: "Radjabova Lobar Ramazonovna", role: "PhD, dotsent" }),
      person({ name: "Fatayeva Farodiba Rustamovna", role: "Assistant" }),
      person({ name: "Shodiev Bakhtiyor", role: "Teacher, trainee" }),
    ],
    preparedSpecialists: [
      program("60811300", "Technology of storage and processing of agricultural products", "bachelor"),
      program("60811800", "Fruit and viticulture", "bachelor"),
      program("60720100", "Food technology (oil and oil products)", "bachelor"),
      program("60720200", "Technology of fats, essential oils and perfumes cosmetics", "bachelor"),
      program("70720101", "Technology of production and processing of food products (oil and oil products)", "master"),
      program("70720701", "Technology of storage and processing of agricultural products", "master"),
      program("02.00.17", "Technologies and biotechnologies for processing, storage and processing of agricultural and food products", "doctoral"),
    ],
    subjects: {
      bachelor: [
        "Biology and genetics",
        "Biophysics and agrometeorology",
        "Botany and plant physiology",
        "Commodity organization of agricultural products",
        "Fruit and vegetable growing",
        "Plant growing",
        "Fundamentals of safety of agricultural products",
        "Physicochemical methods for determining the quality of agricultural products",
        "Technology of storage and processing of fruits and vegetables",
        "Technology of storage and processing of dairy and meat products",
        "Biology of fruit crops",
        "Soil science and agrochemistry",
        "Farming and melioration",
        "Technology of grape cultivation",
        "Vegetable growing and melon growing",
        "Intensive fruit growing",
        "Selection and ampelography of grapes",
        "Chemistry of oils and oily raw materials",
        "Technology of production of vegetable oils",
        "Technology of oil processing",
        "Technology of storage and packaging of oil-and-oil products",
        "Methods and expertise of research of oils and oils",
        "Surfactants in the production of oil-and-oil products",
        "Technology of production of essential oils",
        "Raw materials of perfumery and cosmetic products",
        "Fragrances and dyes",
        "Technology of production of perfume and cosmetic products",
        "Storage and packaging of perfume and cosmetic products",
      ],
      master: [
        "Chemistry of oils and oils",
        "Refining and catalytic modification of oils",
        "Technology of production of solid oils and detergents",
        "Fundamentals of catalysis and potassium",
        "Product expertise of oils and oils",
        "Fundamentals of lubrication of oil-and-oil enterprises",
      ],
    },
    publications: {
      textbooksManuals: [
        publication("Q.Kh.Majidov, F.B.Ashurov, K.K.Sattorov, F.F.Ashurov. Fundamentals of food technology.", "textbook"),
        publication("K.Kh.Majidov, R.A.Makhmudov, N.K.Majidova. Food chemistry and biochemistry.", "textbook"),
        publication("K.Kh.Majidov, S.SH. Ismatov, N.K.Majidova. Technology of oil processing.", "textbook"),
        publication("N.K.Mazhidova, N.N.Sabirova. Food chemistry and biochemistry.", "textbook"),
        publication("K.Kh.Majidov, N.K.Majidova. Technology of production of vegetable oils.", "textbook"),
        publication("Electronic textbook: Q.S.Rakhmonov. Educational research work of students. 2024.", "electronic-textbook"),
        publication("U.K.Khujakulova, N.K.Majidova, A.R.Fayzullaev, Q.S.Rakhmonov, N.F.Khujakulova. Technology of production of vegetable oils. 2024.", "textbook"),
        publication("Q.S.Rakhmonov, L.N.Khaidar-Zade, U.K.Khujakulov, Sh.M.Kurbanova. Technology of production of confectionery products. 2024.", "manual"),
        publication("N.N.Sabirova, Q.Kh.Majidov, N.K.Majidova. Technology of production of perfume and cosmetic products. 2024.", "textbook"),
        publication("Q.Kh.Majidov, U.K.K.Khujakulov, N.K.Majidova, N.N.Sabirova. Raw materials of perfumery, cosmetic products. 2024.", "textbook"),
        publication("A.R.Fayzullaev. Technology of storage and packaging of oil and oil products. 2024.", "textbook"),
        publication("F.N.Ashurov, B.M.Shodiev. Technology of storage and packaging of oil and oil products. 2024.", "electronic-textbook"),
        publication("B.M.Shodiev, F.N.Ashurova. Division of fruit plants into biological economic groups from Technology of cultivation of fruit crops. 2024.", "electronic-textbook"),
        publication("Q.Kh.Majidov, N.K.Majidova, N.N.Sabirova. Technology of production of essential oils. 2024.", "electronic-textbook"),
        publication("M.A.Tursunova, N.K.Majidova. Biology practical training. 2024.", "electronic-textbook"),
        publication("L.N.Khaidar-Zade, Q.S.Rakhmonov, U.M.Ibragimov. Fundamentals of food security, practical lessons in Russian. 2024.", "electronic-textbook"),
        publication("N.R.Dzhuraeva, T.I.Atamuratova, Q.S.Rakhmonov, S.K.Jabbarova. Equipment and basics of design of enterprises for the production of bread, pasta and confectionery. 2024.", "electronic-textbook"),
        publication("L.N.Haidar-Zade, Q.S.Rakhmonov, Sh.Zh.Yuldashev, A.S.Elmurodova, U.M.Ibragimov. Fundamentals of food security. 2024.", "electronic-textbook"),
        publication("Q.S.Rakhmonov, D.I.Umarov, N.Kh.Hakimova, O'. M.Yakyieva. Technology of storage and processing of grain and grain products. 2024.", "electronic-textbook"),
        publication("M.M.Sadikova, N.N.Sabirova, D.J.Khujakulova. General chemical technology. 2024.", "textbook"),
      ],
      articles: [
        publication("Majidov Kakhramon Halimovich, Majidova Nargiza Kakhramonovna. The evalution of catalysts for the hydrogenation of oil sand fats. International Journal of Early Childhood Special Education, 2022."),
        publication("Majidova Nargiza Kakhramonovna. Excellense in detergent production technology. International Journal of Advanced Research in IT and Engineering, 2022."),
        publication("Majidova Nargiza Kakhramonovna. Optimization of Technological Parameters For Deodorization of Vegetable Oils. IJIRSET, 2021."),
        publication("Majidova Nargiza Kakhramonovna. Application of mathematical processing methods for optimizing the hydrogenating catalysts. The American Journal of Engineering and Technology, 2021."),
        publication("Majidov Kakhramon Halimovich. Theoretical approach to the evaluation of catalysts for the hydrogenation of oils and fats. International Journal of Mechanical Engineering, 2022."),
        publication("Majidov Kakhramon Halimovich. The development of an optimal formulation of detergent. IJARSET, 2021."),
        publication("Сабирова Наргиза Нусратовна. Применение полученных шортенинг жиров в маргариновой продукции. Universum, 2020."),
        publication("Сабирова Наргиза Нусратовна. Исследование темперирующих свойств шортенинг-жиров на основе хлопкового масла. UNIVERSUM, 2019."),
        publication("Sabirova Nargiza Nusratovna. Characteristics of new kinds of shortenings. Austrian Journal of Technical and Natural Sciences, 2018."),
        publication("Oltiev Azim To`yqulovich. Improvement of the technology of catalytic hydrogenization of cotton oil. Journal of nutrition and food processing."),
      ],
    },
    research: [
      "Altiev Azim Toykulovich - Improvement of the technology of pereetirization of oil and oil mixture with use of efficient catalysts.",
      "Fayzullaev Askar Rajabboevich - Fundamentals of improvement of the technology for obtaining powdery products from processing of raw materials with roots.",
    ],
    cooperation: [
      "Al-Farabi Kazakh National University.",
      "Karaganda technical university named after A.Saginov.",
      "South Kazakhstan University named after M.Auesov.",
      "University of Copenhagen, Denmark.",
      "University of Extramadura in Spain.",
    ],
    news: [
      "Selection and formation of candidates for targeted doctoral studies or internships in TOP-500 foreign institutions.",
      "Bring scientific potential of the department to 80% and language certificate share to 30%.",
      "Organize 1 SPIN-OFF enterprise and student practice in its workshops.",
      "Develop research based on foreign experience and increase international grants.",
      "Implement foreign investments through existing projects with foreign partners.",
    ],
  },
  "oil-gas-engineering-upstream-downstream": {
    name: "Department of Oil and Gas Engineering (Upstream & Downstream)",
    title: fallback("Department of Oil and Gas Engineering (Upstream & Downstream)"),
    slug: "oil-gas-engineering-upstream-downstream",
    route: "/department/oil-gas-engineering-upstream-downstream",
    aliases: ["/department/oil-and-gas-engineering-upstream-downstream"],
    sourceLink: "https://old.bstu.uz/kafedra/neft-gaz-ishi",
    contact: person({
      name: "Sharipov Qaxramon Qandiyorovich",
      role: "Head of Department",
      title: "Ph.D., associate Professor",
      reception: "Every day 15:00-16:00",
      phone: "+998 93 453 69 69",
      email: "kahramon.sharipov@mail.ru",
    }),
    history: [
      "The Department of Oil and Gas Business was organized on the basis of the Department of Technology of Oil and Gas Chemical Industry according to the new structure approved on July 10, 2019.",
      "The management of the department is entrusted to candidate of chemical sciences, associate professor Q.Q.Sharipov.",
      "At the department 1 doctor of sciences - professor, 1 candidate of sciences - associate professor, 4 doctors of philosophy (PhD), 2 senior teachers, and 2 assistant teachers teach students.",
    ],
    preparedSpecialists: [
      program("60721800", "Oil and gas works (start-up and development of oil and gas fields)", "bachelor"),
      program("5311900", "Oil and gas works (start-up and development of oil and gas fields)", "bachelor"),
      program("5311900", "Start-up and exploitation of oil and gas fields", "bachelor"),
      program("70721802", "The use of machinery and equipment for oil and gas fields", "master"),
      program("5A311902", "The use of machinery and equipment of oil and gas fields", "master"),
    ],
    subjects: {
      bachelor: [
        "Geology of oil and gas",
        "Fundamentals of geophysics",
        "General and underground hydraulics",
        "Fundamentals of oil and gas work",
        "Machinery and equipment of oil and gas fields",
        "Mechanics of rocks",
        "Protection against corrosion",
        "Collection, preparation and transfer of oil and gas",
        "Geology of oil and gas fields",
        "Geophysical control of the operation of oil and gas fields",
        "Drilling of oil and gas wells",
        "Equipment of oil and gas fields",
        "Capital and underground repair of wells",
        "Technology of increasing oil and gas supply of reservoirs",
        "Use of pumping and compressor stations",
      ],
      master: [
        "Machinery and equipment of oil and gas fields",
        "Machinery and equipment for the repair of oil and gas wells",
        "Theoretical foundations of the exploitation of oil and gas fields",
        "Installation and operation of equipment for oil and gas wells",
        "Equipment of oil and gas gathering and preparation facilities in the fields",
      ],
    },
    staff: [
      person({ name: "Sharipov Qakhramon Kandiyorovich", role: "Head of the department, Ph.D., associate Professor" }),
      person({ name: "Dustov Khamro Bozorovich", role: "Professor, Ph.D." }),
      person({ name: "Toshev Sherzod Orzievich", role: "Associate Professor, PhD" }),
      person({ name: "Bozorov Jurabek Toronovich", role: "Associate Professor, PhD" }),
      person({ name: "Ochilov Abdurahim Abdurasulovich", role: "Associate Professor, PhD" }),
      person({ name: "Rakhimov Bobomurod Rustamovich", role: "Assistant, PhD" }),
      person({ name: "Obidov Hamid Olimovich", role: "Senior Lecturer" }),
      person({ name: "Sattorov Mirvohid Olimovich", role: "Senior Lecturer" }),
      person({ name: "Yamaletdinova Aygul Akhmadovna", role: "Assistant" }),
      person({ name: "Bokieva Shakhnoza Komilovna", role: "Assistant" }),
    ],
    scientificMethodicalWorks: [
      "O’quv-uslubiy majmualar - 50 dan ortiq.",
      "Uslubiy qo’llanmalar - 16 ta.",
      "Ma’ruza matnlari - 50 dan ortiq.",
      "Uslubiy ko’rsatmalar - 60 dan ortiq.",
    ],
    scientificArticleCounts: [
      "Xorijiy maqolalar - 150 dan ortiq.",
      "Respublika maqolalari - 200 dan ortiq.",
      "Xalqaro tezislar - 300 dan ortiq.",
      "Respublika tezislari - 250 dan ortiq.",
    ],
    publications: {
      scopusWebOfScience: [
        publication("Toshev Sherzod Orzievich, Obidov Xamid Olimovich. AGRITECH-V-2021. Features of the chemical composition and colloidal-chemical properties of local clays of Uzbekistan and their comparison with other clays, 2021."),
        publication("Ochilov Abduraxim Abdurasulovich, Sattorov Mirvohid Olimovich, Yamaletdinova Aygul Axmadovna, Bokieva Shahnoza Komilovna. Reduction the viscosity of oil-slime emulsions of heavy oils using gas condensate. Earth and Environmental Science, 2021."),
        publication("Sattorov Mirvohid Olimovich, Ochilov Abduraxim Abdurasulovich, Yamaletdinova Aygul Axmadovna, Bokieva Shahnoza Komilovna. Breakdown of local oil-water emulsions by binary systems of surface-active substances. Earth and Environmental Science, 2021."),
        publication("Dustov Xamro Bozorovich. Research the content of waste (yellow oil) of the Shurtan gas chemical complex in Uzbekistan. Journal of Physics: Conference Series, 2021."),
        publication("Dustov Xamro Bozorovich. Fractional composition of the waste yellow oil. IOP Conf. Series: Earth and Environmental Science, 2021."),
        publication("Toshev Sherzod Orzievich. Thermodynamic values of the adsorption of methanol and ethanol molecules in zeolite NH4ZSM-5. IOP Conf. Ser.: Earth Environ. Sci., 2021."),
        publication("Sharipov Qaxramon Qandiyorovich, Bozorov Jo‘rabek To‘ronovich. Key factors reducing energy consumption in gas supply. Earth and Environmental Science, 2021."),
      ],
      textbooksManuals: [],
      monographs: [],
    },
    research: [
      "Create compositions to break up oil and oil emulsions and improve rheological properties.",
      "Creation of polymineral compositions based on local cherries that are resistant to high temperatures and salts.",
      "Development of a technology for the production of odorants based on mercaptans containing natural gas.",
    ],
  },
  "metrology-standardization-quality-control": {
    name: "Metrology, Standardization, and Quality Control",
    title: fallback("Metrology, Standardization, and Quality Control"),
    slug: "metrology-standardization-quality-control",
    route: "/department/metrology-standardization-quality-control",
    aliases: ["/department/metrology-standardization-and-quality-control"],
    sourceLink: "https://old.bstu.uz/kafedra/metrologiya-va-standartlashtirish",
    contact: person({
      name: "Tairov Bakhtiyor Bobokulovich",
      role: "Head of Department",
      title: "DSc / candidate of technical sciences, associate professor",
      reception: "Dushanba-Juma (14:00-16:00 gacha)",
      phone: "+998 93 471 00 65",
      email: "b.toirov@mail.ru",
      image: `${technologyImageBase}/tairov-bakhtiyor-bobokulovich.jpg`,
    }),
    history: [
      "The department began its activity in August 2019 under the name Metrology and standardization on the basis of the newly created structure of the institute.",
      "It trains specialists in 5310900 - Metrology, standardization and product quality management.",
      "There are 13 professors and teachers at the department, with scientific potential of 54%. Over the past two years, 2 PhD works have been defended and teachers have published international textbooks, textbooks, monographs, HAC journal articles and Scopus articles.",
      "The World Bank Academic Innovation Fund AIF-2/20 project Modernization of the system of higher education imported laboratory equipment and introduced virtual laboratories, printed literature and software for training methodologies.",
      "The department prepares competitive specialists in metrology, standardization and certification for manufacturing enterprises of the republic.",
    ],
    projects: [
      "Modernization of the system of higher education.",
      "AIF-2/20 Improving the training of qualified engineers and professional development of professors and teachers based on personalized innovative technologies in higher education institutions.",
      "World Bank Academic Innovation project supporting laboratory equipment, virtual laboratory, printed literature and software.",
    ],
    staff: [
      person({ name: "Tairov Bakhtiyor Bobokulovich", role: "Head of the department, candidate of technical sciences, associate professor", image: `${technologyImageBase}/tairov-bakhtiyor-bobokulovich.jpg` }),
      person({ name: "Qurbanov Abdiraxim Axmedovich", role: "Professor", image: `${technologyImageBase}/qurbanov-abdiraxim-axmedovich.jpg` }),
      person({ name: "Avliyakulov Nadir Nizomovich", role: "Candidate of the technical science, associate professor", image: `${technologyImageBase}/avliyakulov-nadir-nizomovich.jpg` }),
      person({ name: "Hasanova Zebo Davlatovna", role: "PhD, dotsent", image: `${technologyImageBase}/hasanova-zebo-davlatovna.jpg` }),
      person({ name: "Tosheva Gulnora Djurayevna", role: "PhD, dotsent", image: `${technologyImageBase}/tosheva-gulnora-djurayevna.jpg` }),
      person({ name: "Davlyatova Mavlyuda Bakhtiyorovna", role: "PhD, associate professor", image: `${technologyImageBase}/davlyatova-mavlyuda-bakhtiyorovna.jpg` }),
      person({ name: "Boltaeva Zulfiya Zarifovna", role: "PhD, Senior Lecturer" }),
      person({ name: "Sayidakhmedov Ravshan Rajabovich", role: "Senior teacher" }),
      person({ name: "Khojjiyev Administrator Yangibayevich", role: "(PhD) Senior Lecturer", image: `${technologyImageBase}/xojjiyev-mamur-yangiboyevich.jpg` }),
      person({ name: "Khaidarov Shukhrat Khikmatullayevich", role: "Assistant" }),
      person({ name: "Shadiyev Suxrob Sadilloyevich", role: "Assistant" }),
      person({ name: "Qarshiyev Zohid Abdurahim o'g'li", role: "Assistant" }),
      person({ name: "Azimova Firuza Kamolovna", role: "Teacher-trainee", image: `${technologyImageBase}/azimova-firuza-kamolovna.jpg` }),
      person({ name: "Yodgorova Ma'mura Orifovna", role: "Lecturer, trainee" }),
      person({ name: "Kamalova Mukhlisa Khudoyberdievna", role: "Teacher, trainee" }),
    ],
    preparedSpecialists: [
      program("60710800", "Metrology and standardization", "bachelor"),
      program("60711300", "Metrology standardization and product quality management", "bachelor"),
      program("70710802", "Metrologiya, standartlashtirish va sifatni boshqarish", "master"),
    ],
    subjects: {
      bachelor: [
        "Yo‘nalishga kirish",
        "Metrologiya asoslari (NM, AM, QM)",
        "O‘lchashlarning fizikaviy asoslari",
        "O‘lchash usullari va vositalari (EO‘U va A; ITO‘; CBO‘; FKO‘; AO‘)",
        "O‘lchash qurilmalari, elementlari va ularni konstruksiyalash",
        "Ishlab chiqarishning metrologik ta’minoti",
        "Mahsulot sifati va sifatni boshqarishning statistik usullari",
        "O‘lchash vositalarini qiyoslash va kalibrlash",
        "Muvofiqlikni baholash asoslari (SA; MB va A)",
        "Laboratoriyalar kompitentligini baholash",
        "Qiyoslash muhandisligi",
        "Standartlashtirish asoslari",
        "Texnik jihatdan tartibga solish va standartlashtirish",
        "Mahsulot sifat nazorati",
        "Sifat menejment tizimi",
        "Intellektual o‘lchash asboblari",
        "Tovarshunoslik",
        "Tovarlar ekspertizasi",
        "Standartlar va me’yoriy hujjatlarni ishlab chiqish texnologiyasi va ularning ekpestizasi",
        "Kasbiy psixologiya",
      ],
      master: [
        "Ilmiy tadqiqot metodologiyasi",
        "Kvalimetriya va sifatni boshqarishning nazariy asoslari",
        "Avtomatlashtirilgan va intellektual o‘lchash vositlarining nazariy asoslari",
        "Standartlashtirish va texnik jixatdan tartibga solish tizimlarining sifatni boshqarishdagi o‘rni",
        "Eksperimentni tashkil etish va rejalashtirish",
        "Metrologiya, texnik jihatdan tartibga solish, standartlashtirish va sertifikatlashtirishning qonuniy asoslari",
        "Patentshunoslik, lisenziyalash va sertifikatlashtirish",
        "Qayta muhandislik",
        "Maxsus fanlarni o’qitish metodikasi",
        "Ilmiy-tadqiqot ishi va magistrlik disser-tatsiyasini tayyorlash",
        "Ilmiy-pedagogik ish",
        "Ilmiy amaliyot (tajriba orttirish)",
      ],
    },
    publications: {
      textbooksManualsMonographs: [
        publication("Hasanova Z.D. Boshqaruv psixologiyasi. Darslik. 2021 yil", "textbook"),
        publication("Axmetjanov M.M. Kasbiy psixologiya. Darslik. 2021 yil", "textbook"),
        publication("Axmetjanov M.M. Maxsus fanlarni o‘qitish metodikasi. Darslik. 2021 yil", "textbook"),
        publication("Urinov U.K., Turobjonov S.M., Amirqulov N.S., Xo’jjiyev M.Y. Avtomobillarga yoqilg’i quyish shahobchalar va avtomobillarga gaz to’ldirish compressor stansiyalarini qurish va ishlatish. Darslik. 2022 yil", "textbook"),
        publication("Toirov B.B., Yodgorova M.O. Standartlashtirish asoslari. O‘quv qo‘llanma. 2021 yil", "manual"),
        publication("Toirov B.B., Alimov A.A. O‘lchash asboblarini konstruksiyalash. O‘quv qo‘llanma. 2021 yil", "manual"),
        publication("Xaydarov Sh.X. Oziq-ovqat xavfsizligini ta’minlashning asosiy tushunchalari. Uslubiy qo‘llanma. 2019 yil", "manual"),
        publication("Z.Z.Boltaeva. Коллаборативное обучение философия сотрудничества. Monografiya. 2021 yil", "monograph"),
        publication("Axmedjanov M.M. Zamonaviy pedagogik amaliyot - davr talabi. Monografiya. 2021 yil", "monograph"),
        publication("Axmedjanov M.M. Mutaxassislik fanlarida faol o`qitish usullarini tashkil etish texnologiyasi. Monografiya. 2021 yil", "monograph"),
        publication("Axmedjanov M.M. Yodgorova M.O. Tarbiyaviy ishlarni tashkil qilish va boshqarish. Monografiya. 2022 yil", "monograph"),
        publication("Sagdullaev.Sh.Sh, Majidov K.X., Davlyatova M.B. Технология хлебобулочнқх изделий с лечебнопрофилактическими свойствами. Monografiya. 2022 yil", "monograph"),
        publication("Tairov B.B., Alimov A.A., Xo’jjiyev M.Y., Bozorov U.M. O’lchash asboblarini konstruksiyalash. O’quv-qo’llanma. 2022 yil", "manual"),
        publication("Tosheva G.Dj. Bo‘lajak mutaxassislarni amaliy o‘qitish asosida dizaynerlik faoliyatiga tayyorlash metodikasini takomillashtirish. Monografiya. 2023 yil", "monograph"),
        publication("Yodgorova M.O. Faol metodlaridan foydalanish-zamon talabi. Monografiya. 2023 yil", "monograph"),
        publication("Gaffarov A.X. LMS MOODLE tizimida interaktiv elementlarni yaratish texnologiyasi. Monografiya. 2023 yil", "monograph"),
        publication("R.T.Adizov, N.X. Qobilova. Don va don mahsulotlarini saqlash texnologiyasi. Darslik. 2023 yil", "textbook"),
        publication("Kurbanov A.A. Ilmiy tadqiqot metodologiyasi. O‘quv qo‘llanma. 2023 yil", "manual"),
        publication("Avliyakulov N.N. Metrologiya, standartlashtirish va sertifikatlashtirish asoslari. O‘quv qo‘llanma. 2023 yil", "manual"),
        publication("Avliyakulov N.N. Metrologiya, standartlashtirish va sertifikatlashtirish. Elektron darslik.", "electronic-textbook"),
      ],
    },
    research: [
      "Kamalova Muxlisa Xudoyberdiyevna - Xalqaro standartlar asosida oziq-ovqat mahsulotlarini ishlab chiqarish, sifat jarayonlarini nazorat qilish tizimini takomillashtirish",
      "Yodgorova Ma’mura Orifovna - Noan’anviy ta’sir qilish usullarini qo‘llash asosida igna bargli o‘simliklarni ekstraksiyalash jarayonini takomillashtirish",
      "Sayidaxmedov Ravshan Rajabovich - Mahalliy sharoitda etishtirilgan bug’doy uni kleykovinasini quritish jarayonini akustik ishlov berish bilan takomillashtirish",
      "Shadiyev Suxrob Sadilloyevich - Qandolat mahsulotlarning sifatini kompleksli baholash tizimini takomillashtirish",
      "Xaydarov Shuxrat Xikmatilloyevich - Past alkogolli va alkogolsiz ichimliklar ishlab chiqarishda fitoqo‘shimchalardan foydalanib istiqbolli texnologiyasini ishlab chiqish",
      "Azimova Feruza Kamolovna - Bo’lajak muhandislarning kasbiy ko’nikmalarini metakognitiv yondashuv asosida shakllantirish metodikasi",
    ],
    cooperation: [
      "Strategic cooperation memorandum with M.Auezov South Kazakhstan State University.",
      "Cooperation with al-Farabi Kazakh National University and the Heat Physics and Technical Physics department of the Faculty of Physics.",
      "Joint master's program for 70710800 Metrology, standardization and quality management for 2025-2026.",
    ],
    prospectivePlans: [
      "Training specialists that meet market demands through part-time education.",
      "Retraining courses for specialists in metrology, standardization, certification and quality management.",
      "Practical training, laboratory work and internships in industrial enterprises.",
      "Certificates recognized by the National Agency for Standardization of the Republic of Uzbekistan.",
      "Creation of textbooks and teaching aids with latest modern metrology and standardization information.",
      "Implementation of open educational resources and distance learning materials.",
      "Adapting educational programs to the Bologna process.",
      "Modern research in measuring instruments, precision standards, certification and quality management.",
      "Updating laboratory equipment with measuring instruments, calibration stands and certification equipment.",
      "Simulation software for metrological measurement processes.",
      "Creation of an electronic portal for department control and student communication.",
      "Training specialists on ISO 9001, ISO/IEC 17025, and ISO 14001.",
      "Expansion of practice sites in industrial enterprise metrology laboratories.",
      "Participation in Erasmus+, Tempus, Fulbright and other international grant programs.",
      "Attraction of foreign specialists for training and scientific work.",
    ],
  },
};

export const technologyDepartments = TECHNOLOGY_DEPARTMENT_SLUGS.map((slug) => ({
  facultyId: TECHNOLOGY_FACULTY_ID,
  sourceDocument,
  sourceOfTruth: sourceDocument,
  rawContent: {
    original: rawByDepartment[slug] || "",
    fullRequirements: requirementsText,
  },
  ...departments[slug],
}));

const normalizeRouteInput = (route) => {
  if (!route) return "";

  return String(route)
    .trim()
    .replace(/^https?:\/\/[^/]+/i, "")
    .split("?")[0]
    .split("#")[0]
    .replace(/^\/department\//, "")
    .replace(/^\/+|\/+$/g, "");
};

export function getTechnologyDepartmentBySlug(slug) {
  const normalizedSlug = technologyDepartmentRouteAliases[slug] || slug;
  return technologyDepartments.find((department) => department.slug === normalizedSlug) || null;
}

export function getTechnologyDepartmentByRoute(route) {
  return getTechnologyDepartmentBySlug(normalizeRouteInput(route));
}

export function getFacultyTechnologyRouteData() {
  return {
    faculty: facultyTechnology,
    departments: technologyDepartments,
    routes: {
      faculty: facultyTechnology.route,
      departments: technologyDepartments.flatMap((department) => [
        department.route,
        ...(department.aliases || []),
      ]),
    },
    aliases: technologyDepartmentRouteAliases,
    sourceDocument,
  };
}

export const facultyTechnologyRawRequirements = requirementsText;
export const facultyTechnologyImagePaths = {
  deanImages,
  existingFallbackImages,
  oilRefiningImageBase,
  foodImageBase,
  technologyImageBase,
  webImage,
};
