export const videosData = [
  {
    "id": "graduation-2026",
    "isLocal": true,
    "videoUrl": "/assets/video/graduation-2026.mp4",
    "poster": "/assets/img/hero-university.jpg",
    "title": "BSTU Graduation Ceremony - Class of 2026",
    "category": "Campus Life",
    "duration": "4:15",
    "views": "5.2K views",
    "date": "1 week ago",
    "description": "Witness the highlights of the graduation ceremony for the class of 2026 at Bukhara State Technical University. We are proud of our graduates and wish them success in their future engineering careers."
  },
  {
    "id": "a4mTYkutUgQ",
    "youtubeId": "a4mTYkutUgQ",
    "poster": "https://img.youtube.com/vi/a4mTYkutUgQ/hqdefault.jpg",
    "title": "#jarayon",
    "category": "Campus Life",
    "duration": "0:48",
    "views": "16 views",
    "date": "2 months ago",
    "description": "Highlights from academic and practical processes"
  },
  {
    "id": "yDFgDyXhSAM",
    "youtubeId": "yDFgDyXhSAM",
    "poster": "https://img.youtube.com/vi/yDFgDyXhSAM/hqdefault.jpg",
    "title": "#Engineering_Month",
    "category": "Academics",
    "duration": "0:48",
    "views": "5 views",
    "date": "3 months ago",
    "description": "Events organized during the Engineering Month"
  },
  {
    "id": "fVeRnsg7i2E",
    "youtubeId": "fVeRnsg7i2E",
    "poster": "https://img.youtube.com/vi/fVeRnsg7i2E/hqdefault.jpg",
    "title": "#Muhandislik_oyligi",
    "category": "Academics",
    "duration": "0:48",
    "views": "13 views",
    "date": "3 months ago",
    "description": "Engineering Month at Bukhara State Technical University"
  },
  {
    "id": "MSGRN0M63vc",
    "youtubeId": "MSGRN0M63vc",
    "poster": "https://img.youtube.com/vi/MSGRN0M63vc/hqdefault.jpg",
    "title": "#jarayon",
    "category": "Campus Life",
    "duration": "1:41",
    "views": "7 views",
    "date": "3 months ago",
    "description": "Process snapshots from educational and scientific laboratories"
  },
  {
    "id": "79g1io9OrKg",
    "youtubeId": "79g1io9OrKg",
    "poster": "https://img.youtube.com/vi/79g1io9OrKg/hqdefault.jpg",
    "title": "#Rahbar_va_yoshlar_uchrashuvi",
    "category": "Campus Life",
    "duration": "1:37",
    "views": "8 views",
    "date": "3 months ago",
    "description": "Meeting between the rector and the university youth"
  },
  {
    "id": "N5exeY-Kk8g",
    "youtubeId": "N5exeY-Kk8g",
    "poster": "https://img.youtube.com/vi/N5exeY-Kk8g/hqdefault.jpg",
    "title": "#Dayjest #21mart",
    "category": "Campus Life",
    "duration": "1:10",
    "views": "9 views",
    "date": "3 months ago",
    "description": "March 21 Navruz holiday celebration digest"
  },
  {
    "id": "GvJspSc4wnQ",
    "youtubeId": "GvJspSc4wnQ",
    "poster": "https://img.youtube.com/vi/GvJspSc4wnQ/hqdefault.jpg",
    "title": "#podkast",
    "category": "Academics",
    "duration": "7:15",
    "views": "50 views",
    "date": "3 months ago",
    "description": "Scientific podcast with young scientists and students"
  },
  {
    "id": "mIacRgR7Wog",
    "youtubeId": "mIacRgR7Wog",
    "poster": "https://img.youtube.com/vi/mIacRgR7Wog/hqdefault.jpg",
    "title": "#bayram_shukuhi",
    "category": "Campus Life",
    "duration": "1:23",
    "views": "12 views",
    "date": "3 months ago",
    "description": "Festive atmosphere and spring celebrations at the university"
  },
  {
    "id": "yuUl38PLcVs",
    "youtubeId": "yuUl38PLcVs",
    "poster": "https://img.youtube.com/vi/yuUl38PLcVs/hqdefault.jpg",
    "title": "#kelajak_muhanddislari",
    "category": "Research",
    "duration": "3:56",
    "views": "7 views",
    "date": "3 months ago",
    "description": "Exhibition of the Future Engineers Festival at BSTU"
  },
  {
    "id": "sZMHhW3KlrM",
    "youtubeId": "sZMHhW3KlrM",
    "poster": "https://img.youtube.com/vi/sZMHhW3KlrM/hqdefault.jpg",
    "title": "#Prezident_topshirig‘i_ijrosi",
    "category": "Research",
    "duration": "1:52",
    "views": "13 views",
    "date": "3 months ago",
    "description": "Practical results of implementing President instructions"
  },
  {
    "id": "loj5daDxQfM",
    "youtubeId": "loj5daDxQfM",
    "poster": "https://img.youtube.com/vi/loj5daDxQfM/hqdefault.jpg",
    "title": "bayram 8mart",
    "category": "Campus Life",
    "duration": "1:40",
    "views": "7 views",
    "date": "3 months ago",
    "description": "Festive event dedicated to International Women's Day on March 8"
  },
  {
    "id": "pW8mTZS0K2I",
    "youtubeId": "pW8mTZS0K2I",
    "poster": "https://img.youtube.com/vi/pW8mTZS0K2I/hqdefault.jpg",
    "title": "#jarayon",
    "category": "Campus Life",
    "duration": "0:59",
    "views": "20 views",
    "date": "4 months ago",
    "description": "BSTU innovative ideas and startups snapshots"
  },
  {
    "id": "eFMgy1ia3DM",
    "youtubeId": "eFMgy1ia3DM",
    "poster": "https://img.youtube.com/vi/eFMgy1ia3DM/hqdefault.jpg",
    "title": "Inklyuziv ta’lim — teng imkoniyatlar asosi",
    "category": "Academics",
    "duration": "0:58",
    "views": "8 views",
    "date": "4 months ago",
    "description": "Inclusive education - the foundation of equal opportunities for all"
  },
  {
    "id": "aqYQJlLuy2A",
    "youtubeId": "aqYQJlLuy2A",
    "poster": "https://img.youtube.com/vi/aqYQJlLuy2A/hqdefault.jpg",
    "title": "#BIMO_2026",
    "category": "Academics",
    "duration": "1:02",
    "views": "12 views",
    "date": "4 months ago",
    "description": "Bukhara International Mathematics Olympiad (BIMO 2026)"
  },
  {
    "id": "diNs5LCoKqU",
    "youtubeId": "diNs5LCoKqU",
    "poster": "https://img.youtube.com/vi/diNs5LCoKqU/hqdefault.jpg",
    "title": "#Ma’rifat_targ‘ibotchilari",
    "category": "Campus Life",
    "duration": "0:34",
    "views": "8 views",
    "date": "4 months ago",
    "description": "Spiritual and educational event by Enlightenment promoters"
  },
  {
    "id": "s3m2FC7p618",
    "youtubeId": "s3m2FC7p618",
    "poster": "https://img.youtube.com/vi/s3m2FC7p618/hqdefault.jpg",
    "title": "TALABALAR QORDA",
    "category": "Campus Life",
    "duration": "1:36",
    "views": "24 views",
    "date": "5 months ago",
    "description": "BSTU students enjoying the snowy winter days"
  },
  {
    "id": "fNnzuHRFy4U",
    "youtubeId": "fNnzuHRFy4U",
    "poster": "https://img.youtube.com/vi/fNnzuHRFy4U/hqdefault.jpg",
    "title": "#bayram_shukuhi",
    "category": "Campus Life",
    "duration": "1:35",
    "views": "10 views",
    "date": "5 months ago",
    "description": "Festive events and activities on the eve of the New Year"
  },
  {
    "id": "C7DRBQzYW4c",
    "youtubeId": "C7DRBQzYW4c",
    "poster": "https://img.youtube.com/vi/C7DRBQzYW4c/hqdefault.jpg",
    "title": "#oav_biz_haqimizda",
    "category": "Research",
    "duration": "3:45",
    "views": "6 views",
    "date": "5 months ago",
    "description": "Mass media about us - TV reports and news highlights"
  },
  {
    "id": "HXTP8W0ExMU",
    "youtubeId": "HXTP8W0ExMU",
    "poster": "https://img.youtube.com/vi/HXTP8W0ExMU/hqdefault.jpg",
    "title": "#bayram_shukuhi",
    "category": "Campus Life",
    "duration": "1:41",
    "views": "10 views",
    "date": "5 months ago",
    "description": "Constitution Day celebrations and activities"
  },
  {
    "id": "GuBhY7XL1uI",
    "youtubeId": "GuBhY7XL1uI",
    "poster": "https://img.youtube.com/vi/GuBhY7XL1uI/hqdefault.jpg",
    "title": "#bayram_shukuhi",
    "category": "Campus Life",
    "duration": "0:51",
    "views": "16 views",
    "date": "5 months ago",
    "description": "Festive event in the student dormitory"
  },
  {
    "id": "PeO011rG1MI",
    "youtubeId": "PeO011rG1MI",
    "poster": "https://img.youtube.com/vi/PeO011rG1MI/hqdefault.jpg",
    "title": "#bayram_shukuhi",
    "category": "Campus Life",
    "duration": "0:32",
    "views": "13 views",
    "date": "5 months ago",
    "description": "Awarding the winners of sports competitions"
  },
  {
    "id": "EmI0y8mHTgE",
    "youtubeId": "EmI0y8mHTgE",
    "poster": "https://img.youtube.com/vi/EmI0y8mHTgE/hqdefault.jpg",
    "title": "#video",
    "category": "Campus Life",
    "duration": "1:23",
    "views": "22 views",
    "date": "5 months ago",
    "description": "Video clip showcasing vibrant university event highlights"
  },
  {
    "id": "DNlLZpSYKUY",
    "youtubeId": "DNlLZpSYKUY",
    "poster": "https://img.youtube.com/vi/DNlLZpSYKUY/hqdefault.jpg",
    "title": "Diyorbek Ergashov",
    "category": "Research",
    "duration": "2:04",
    "views": "64 views",
    "date": "6 months ago",
    "description": "Achievements of Bukhara State Technical University student Diyorbek Ergashov"
  },
  {
    "id": "KujaDfrMQ78",
    "youtubeId": "KujaDfrMQ78",
    "poster": "https://img.youtube.com/vi/KujaDfrMQ78/hqdefault.jpg",
    "title": "#To'garak",
    "category": "Campus Life",
    "duration": "0:47",
    "views": "8 views",
    "date": "6 months ago",
    "description": "Activities of academic and creative clubs at the university"
  },
  {
    "id": "q8EqS6vv-e8",
    "youtubeId": "q8EqS6vv-e8",
    "poster": "https://img.youtube.com/vi/q8EqS6vv-e8/hqdefault.jpg",
    "title": "Kasaba uyushmasi taqdirlash marosimi",
    "category": "Campus Life",
    "duration": "0:26",
    "views": "16 views",
    "date": "6 months ago",
    "description": "Awarding ceremony of the trade union staff and members"
  },
  {
    "id": "nL0LEGH9n7g",
    "youtubeId": "nL0LEGH9n7g",
    "poster": "https://img.youtube.com/vi/nL0LEGH9n7g/hqdefault.jpg",
    "title": "TALABALAR PLANETASI — 2-QISM",
    "category": "Campus Life",
    "duration": "24:00",
    "views": "50 views",
    "date": "6 months ago",
    "description": "🎓 STUDENT PLANET — PART 2 'Plagiarist or Motivator'"
  },
  {
    "id": "FPq81ioHghs",
    "youtubeId": "FPq81ioHghs",
    "poster": "https://img.youtube.com/vi/FPq81ioHghs/hqdefault.jpg",
    "title": "Talabalar Planetasi — 1-qism",
    "category": "Campus Life",
    "duration": "13:32",
    "views": "36 views",
    "date": "6 months ago",
    "description": "🌍 'Student Planet' — Part 1: 'The New Student'"
  },
  {
    "id": "LPfUdQsLgj4",
    "youtubeId": "LPfUdQsLgj4",
    "poster": "https://img.youtube.com/vi/LPfUdQsLgj4/hqdefault.jpg",
    "title": "Konstitutsiya qabul qilinganligining 33 yillligi",
    "category": "Campus Life",
    "duration": "1:07",
    "views": "23 views",
    "date": "7 months ago",
    "description": "On the occasion of the 33rd anniversary of the adoption of the Constitution of the Republic of Uzbekistan"
  },
  {
    "id": "ON_zcrebqSM",
    "youtubeId": "ON_zcrebqSM",
    "poster": "https://img.youtube.com/vi/ON_zcrebqSM/hqdefault.jpg",
    "title": "Davlat bayrog‘i yurish marafoni",
    "category": "Campus Life",
    "duration": "1:43",
    "views": "8 views",
    "date": "7 months ago",
    "description": "Walking marathon dedicated to the 34th anniversary of the adoption of the State Flag"
  },
  {
    "id": "sJnd3nsvxK8",
    "youtubeId": "sJnd3nsvxK8",
    "poster": "https://img.youtube.com/vi/sJnd3nsvxK8/hqdefault.jpg",
    "title": "Oilani mustahkamlash siyosati",
    "category": "Academics",
    "duration": "2:48",
    "views": "11 views",
    "date": "7 months ago",
    "description": "State policy based on family strengthening in Turkey and Uzbekistan seminar"
  }
];
