output_buffering = 4096
error_reporting = E_ALL & ~E_DEPRECATED
display_errors = Off
default_charset = "UTF-8"
upload_max_filesize = 200M
post_max_size = 220M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300
sys_temp_dir = "c:/Users/KAPAKA/Desktop/international.bstu.uz/apps/api/storage/temp"
upload_tmp_dir = "c:/Users/KAPAKA/Desktop/international.bstu.uz/apps/api/storage/temp"
extension_dir = "C:\Program Files\PHP\8.5.7\nts\x64\ext"
extension=curl
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=mysqli
extension=fileinfo
extension=sodium
