output_buffering = 4096
error_reporting = E_ALL & ~E_DEPRECATED
display_errors = Off
default_charset = "UTF-8"
extension_dir = "C:\Program Files\PHP\8.5.7\nts\x64\ext"
extension=curl
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=mysqli
extension=fileinfo
extension=sodium
